import { useRef, useState } from 'react';
import { snapAssemblyPoint } from '../calculations/roof-drawings.js';
import { pointerDragged } from '../planner/interactions.js';

const layerNames={roof:'Контур кровли',rooms:'Стены и комнаты',openings:'Проёмы',rafters:'Стропила',roofTimbers:'Мауэрлат и конёк',laths:'Обрешётка',counterLaths:'Контробрешётка',supports:'Опоры',binding:'Обвязка',piles:'Фундамент',panels:'Панели потолка',labels:'Марки и размеры'};
export default function AssemblyCanvas({assembly,onPick,onMove,draft,initialFloor,onSelect,selected,onMovePoint,onTranslate,onFloorChange}) {
  const drag=useRef(null),[dragPreview,setDragPreview]=useState(null);
  const [snap,setSnap]=useState(true);
  const [panelLevel,setPanelLevel]=useState('ceiling');
  const [zoom,setZoom]=useState(1);
  const panelPreset=level=>{setPanelLevel(level);setLayers(Object.fromEntries(Object.keys(layerNames).map(k=>[k,['rooms','openings','supports','panels','labels'].includes(k)])));};
  const [floor,setFloor]=useState(initialFloor||assembly.floors.at(-1)?.floor||1);
  const [layers,setLayers]=useState(()=>Object.fromEntries(Object.keys(layerNames).map(k=>[k,true])));
  const plan=assembly.floors.find(p=>p.floor===floor)||assembly.floors[0];
  if(!plan?.contour.length)return <p>Задайте контур дома.</p>;
  const {x,y,width,height}=assembly.bounds,pad=Math.max(width,height)*.14,font=Math.max(width,height)*.02;
  const points=items=>items.map(p=>p.slice(0,2).join(',')).join(' ');
  const locate=(event,handler)=>{if(!handler)return;const svg=event.currentTarget.ownerSVGElement||event.currentTarget,m=svg.getScreenCTM();if(!m)return;const p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;const q=p.matrixTransform(m.inverse());const xy=snap?snapAssemblyPoint(assembly,q.x,q.y,Math.max(width,height)*.008):[Math.round(q.x/10)*10,Math.round(q.y/10)*10];handler(...xy);};
  const move=e=>{if(drag.current){if(pointerDragged(drag.current.start,e))locate(e,(x,y)=>setDragPreview({...drag.current,point:[x,y]}));}else locate(e,onMove);};
  const end=e=>{if(!drag.current)return;const target=drag.current;if(pointerDragged(target.start,e))locate(e,(x,y)=>target.translate?onTranslate?.(target.id,x-target.origin[0],y-target.origin[1]):onMovePoint?.(target.id,target.end,x,y));drag.current=null;setDragPreview(null);};
  const line=(a,b,{key,...props})=> <line key={key} x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} vectorEffect="non-scaling-stroke" {...props}/>;
  return <div className="cut-assembly"><div className="cut-tabs assembly-controls">{assembly.floors.map(p=><button key={p.floor} aria-pressed={floor===p.floor} onClick={()=>{setFloor(p.floor);onFloorChange?.(p.floor);}}>План {p.floor} этажа</button>)}<button onClick={()=>setLayers(Object.fromEntries(Object.keys(layerNames).map(k=>[k,true])))}>Все слои</button><button onClick={()=>setLayers(Object.fromEntries(Object.keys(layerNames).map(k=>[k,false])))}>Скрыть слои</button><button onClick={()=>panelPreset('ceiling')}>Панели потолка сверху</button><button onClick={()=>panelPreset('floor')}>Панели пола сверху</button></div>
    <div className="cut-tabs assembly-controls">{Object.entries(layerNames).map(([key,name])=><label className="cut-check" key={key}><input type="checkbox" checked={layers[key]} onChange={e=>setLayers({...layers,[key]:e.target.checked})}/>{key==='panels'&&panelLevel==='floor'?'Панели пола':name}</label>)}</div>
    {onPick||onSelect?<label className="cut-check assembly-controls"><input type="checkbox" checked={snap} onChange={e=>setSnap(e.target.checked)}/>Привязка к стенам, опорам и соединителям панелей</label>:null}
    <div className="cut-tabs assembly-controls"><button onClick={()=>setZoom(Math.max(1,zoom/1.5))}>Отдалить план</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(Math.min(6,zoom*1.5))}>Приблизить план</button><button onClick={()=>setZoom(1)}>Весь план</button></div>
    <svg viewBox={`${(assembly.supports.find(s=>zoom>1&&s.id===selected)?.a[0]??x+width/2)-(width+2*pad)/zoom/2} ${(assembly.supports.find(s=>zoom>1&&s.id===selected)?.a[1]??y+height/2)-(height+2*pad)/zoom/2} ${(width+2*pad)/zoom} ${(height+2*pad)/zoom}`} aria-label="Совмещённый монтажный план" role="img" onClick={e=>locate(e,onPick)} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{drag.current=null;setDragPreview(null);}} style={{cursor:onPick?'crosshair':'default',touchAction:onPick||selected?'none':'auto'}}>
      {layers.roof?<polygon points={points(assembly.roofOutline)} fill="#eaf1f7" stroke="#345d86" strokeWidth="1" vectorEffect="non-scaling-stroke"/>:null}
      {layers.rooms?<><polygon points={points(plan.contour)} fill="white" fillOpacity=".6" stroke="#000" strokeWidth="2" vectorEffect="non-scaling-stroke"/>{plan.rooms.map((r,i)=><g key={i}><polygon points={points(r.points)} fill="none" stroke="#888" vectorEffect="non-scaling-stroke"/>{layers.labels?<text x={r.points.reduce((s,p)=>s+p[0],0)/r.points.length} y={r.points.reduce((s,p)=>s+p[1],0)/r.points.length} fontSize={font} textAnchor="middle">{r.name}</text>:null}</g>)}{(plan.bearing||[]).map((e,i)=>line(e.a,e.b,{key:i,stroke:'#25734d',strokeWidth:4}))}</>:null}
      {layers.panels?(panelLevel==='floor'?assembly.floorPanelLayers||[]:assembly.panelLayers||[]).filter(p=>p.floor===floor).map(p=><g key={p.id}><path d={p.shape.map(r=>r.map((q,i)=>`${i?'L':'M'}${q.join(',')}`).join(' ')+'Z').join(' ')} fill="#e5efdf" fillOpacity=".4" fillRule="evenodd" stroke="#609047" strokeWidth="1" vectorEffect="non-scaling-stroke"/>{layers.labels?<text x={p.x+p.width/2} y={p.y+p.height/2} fontSize={font*.7} textAnchor="middle">{p.displayMark||p.id.replace(/^.*-P/,'П')}</text>:null}</g>):null}
      {layers.panels?(assembly.panelConnectors||[]).filter(m=>m.surfaceId===`Э${floor}-${panelLevel==='floor'?'ПОЛ':'ПТ'}`).map(m=>line(m.a,m.b,{key:m.id,stroke:'#a06e32',strokeWidth:2})):null}
      {layers.binding?(assembly.binding||[]).map(s=>line(s.a,s.b,{key:s.id,stroke:'#8c652d',strokeWidth:4})):null}
      {layers.piles?(assembly.piles||[]).map((p,i)=><rect key={i} x={p[0]-font*.15} y={p[1]-font*.15} width={font*.3} height={font*.3} fill="#333"/>):null}
      {layers.openings?plan.openings.map((o,i)=>{const v=o.orientation==='v';return line([o.x-(v?0:o.width/2),o.y-(v?o.width/2:0)],[o.x+(v?0:o.width/2),o.y+(v?o.width/2:0)],{key:i,stroke:o.type==='window'?'#347196':'#bd7b30',strokeWidth:5});}):null}
      {layers.rafters?assembly.rafters.map(r=>line(r.a,r.b,{key:r.id,stroke:'#879baf',strokeWidth:1})):null}
      {layers.roofTimbers?(assembly.roofTimbers||[]).map(r=>line(r.a,r.b,{key:r.id,stroke:'#6f4b23',strokeWidth:3})):null}
      {layers.laths?(assembly.laths||[]).map(r=>line(r.a,r.b,{key:r.id,stroke:'#a78747',strokeWidth:.7})):null}
      {layers.counterLaths?(assembly.counterLaths||[]).map(r=>line(r.a,r.b,{key:r.id,stroke:'#735534',strokeWidth:2})):null}
      {layers.roof&&assembly.ridge.length===2?line(...assembly.ridge,{stroke:'#345d86',strokeWidth:2,strokeDasharray:'8 4'}):null}
      {layers.supports?assembly.supports.map(s=>{const translated=dragPreview?.id===s.id&&dragPreview.translate,shift=p=>translated?p.map((n,i)=>i<2?n+dragPreview.point[i]-dragPreview.origin[i]:n):p;const a=dragPreview?.id===s.id&&dragPreview.end===1?dragPreview.point:shift(s.a),b=dragPreview?.id===s.id&&dragPreview.end===2?dragPreview.point:shift(s.b);return <g key={s.id} role={onSelect?'button':undefined} tabIndex={onSelect?0:undefined} aria-label={`Выбрать ${s.mark}`} onPointerDown={e=>{if(onPick||!onSelect||e.button!==0)return;e.stopPropagation();if(selected!==s.id){onSelect(s.id);return;}if(onTranslate){e.preventDefault();locate(e,(x,y)=>{drag.current={id:s.id,translate:true,origin:[x,y],start:{x:e.clientX,y:e.clientY}};});e.currentTarget.setPointerCapture(e.pointerId);}}} onClick={e=>{if(!onPick&&onSelect){e.stopPropagation();onSelect(s.id);}}} onKeyDown={e=>{if(onSelect&&['Enter',' '].includes(e.key)){e.preventDefault();onSelect(s.id);}}}>
        {line(a,b,{stroke:'transparent',strokeWidth:20})}{line(a,b,{stroke:selected===s.id?'#146ec1':'#a85528',strokeWidth:3,strokeDasharray:'8 5'})}<circle cx={a[0]} cy={a[1]} r={font*.16} fill="#a85528"/>{layers.labels?<text x={(a[0]+b[0])/2} y={(a[1]+b[1])/2-font*.5} fontSize={font} textAnchor="middle">{s.mark} · {dragPreview?.id===s.id?Math.round(Math.hypot(b[0]-a[0],b[1]-a[1]))+' в плане':s.length} мм</text>:null}
        {selected===s.id&&onMovePoint&&!onPick?[a,b].map((p,i)=><circle key={i} aria-label={`${s.mark}: ${i?'конец':'начало'}`} cx={p[0]} cy={p[1]} r={font*.45} fill="white" stroke="#146ec1" strokeWidth="2" vectorEffect="non-scaling-stroke" onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();drag.current={id:s.id,end:i+1,start:{x:e.clientX,y:e.clientY}};e.currentTarget.setPointerCapture(e.pointerId);}}/>):null}
      </g>;}):null}
      {draft?<g>{line(draft.a,draft.b,{stroke:'#000',strokeWidth:2,strokeDasharray:'6 4'})}<text x={draft.b[0]} y={draft.b[1]-font} fontSize={font}>{Math.round(Math.hypot(draft.b[0]-draft.a[0],draft.b[1]-draft.a[1]))} мм</text></g>:null}
      {(assembly.nodes||[]).map((n,i)=>{const id='node:'+n.id,preview=dragPreview?.id===id,dx=preview?dragPreview.point[0]-dragPreview.origin[0]:0,dy=preview?dragPreview.point[1]-dragPreview.origin[1]:0;return n.floor===floor?<g key={n.id} role={onSelect?'button':undefined} tabIndex={onSelect?0:undefined} aria-label={`Выбрать узел У-${i+1}`} onPointerDown={e=>{if(onPick||!onSelect||e.button!==0)return;e.stopPropagation();if(selected!==id){onSelect(id);return;}if(onTranslate){e.preventDefault();locate(e,(x,y)=>{drag.current={id,translate:true,origin:[x,y],start:{x:e.clientX,y:e.clientY}};});e.currentTarget.setPointerCapture(e.pointerId);}}} onClick={e=>{if(onSelect&&!onPick){e.stopPropagation();onSelect(id);}}} onKeyDown={e=>{if(onSelect&&['Enter',' '].includes(e.key)){e.preventDefault();onSelect(id);}}}><circle cx={n.x+dx} cy={n.y+dy} r={font*.5} fill={selected===id?'#cce0d3':'white'} stroke="#000" strokeWidth="2" vectorEffect="non-scaling-stroke"/><text x={n.x+dx+font*.7} y={n.y+dy} fontSize={font}>У-{i+1}{n.nodeRef?` · ${n.nodeRef}`:''}</text></g>:null;})}
      {layers.labels?<g><text x={x+width/2} y={y+height+pad*.65} fontSize={font} textAnchor="middle">{width} мм</text><text x={x-pad*.6} y={y+height/2} fontSize={font} textAnchor="middle" transform={`rotate(-90 ${x-pad*.6} ${y+height/2})`}>{height} мм</text></g>:null}
    </svg><p>Пунктир — проектные линии опор. Зелёным выделены выбранные несущие стены. Размеры в мм; несущую способность и узлы подтверждает проектировщик.</p>
  </div>;
}
