import { useMemo } from 'react';
import { calculateTerraceRoof } from '../../calculations/terrace-model.js';
import { useProject } from '../state/ProjectContext.jsx';
import { calculateProject } from '../calculations/estimate-engine.js';
import { NumberField, Panel, PreviewTable, ScreenHeader, SelectField, Stat, Toggle } from '../components/ui.jsx';
import { formatNumber } from '../utils/format.js';

const TITLES = {
  piles: ['Свайное поле и обвязка', 'Дом и пристройки считаются как единая геометрия без повторяющихся свай'],
  sip: ['СИП-конструкции', 'Пол, наружные стены, потолок, перегородки, проёмы и раскрой'],
  roof: ['Кровля', 'Основная крыша и кровли террас считаются отдельно, затем объединяются в ведомость'],
  terrace: ['Терраса и крыльцо', 'Настил, каркас, ступени и конструктивные параметры каждой площадки'],
  openings: ['Окна и двери', 'Проёмы берутся непосредственно с плана дома'],
  engineering: ['Инженерные системы', 'Электрика, водоснабжение, канализация и вентиляция'],
  finishing: ['Отделка', 'Внутренняя и наружная комплектация с точными площадями'],
  delivery: ['Доставка и логистика', 'Рейсы, расстояние, объём и погрузочно-разгрузочные работы']
};

function SectionResult({ calculation, sectionKey }) {
  const section = calculation.sections.find((item) => item.key === sectionKey);
  return <PreviewTable lines={section?.lines || []} />;
}

export default function Calculators({ type }) {
  const { project: sourceProject, commit } = useProject();
  const calculation = useMemo(() => calculateProject(sourceProject), [sourceProject]);
  const project = useMemo(() => ({
    ...sourceProject,
    settings: {
      ...sourceProject.settings,
      roof: { ...sourceProject.settings.roof, ridgeLength: calculation.inputs.roof.ridgeLength },
      engineering: calculation.inputs.engineering,
      internal: { ...sourceProject.settings.internal, ...calculation.inputs.internal },
      external: { ...sourceProject.settings.external, ...calculation.inputs.external },
      delivery: { ...sourceProject.settings.delivery, cargoVolume: calculation.inputs.delivery.cargoVolume }
    }
  }), [sourceProject, calculation.inputs]);
  const setSetting = (group, key, value) => commit((next) => {
    next.settings[group][key] = value;
    if (group === 'engineering') next.settings.links.engineeringFromPlan = false;
    if (group === 'internal') next.settings.links.internalFinishFromPlan = false;
    if (group === 'external') next.settings.links.externalFinishFromPlan = false;
    if (group === 'roof' && key === 'ridgeLength') next.settings.links.roofRidgeFromPlan = false;
    if (group === 'delivery' && key === 'cargoVolume') next.settings.links.deliveryVolumeFromPlan = false;
    return next;
  });
  const setService = (key, value) => commit((next) => { next.services[key] = value; return next; });
  const [title, description] = TITLES[type] || TITLES.piles;
  return <div className="screen"><ScreenHeader title={title} description={description} />
    <div className="calculation-link-banner"><strong>Данные связаны с планом</strong><span>Поля с расчётными значениями обновляются автоматически. Ручное изменение такого поля отключает соответствующую связь; включить её снова можно кнопкой ⚙ вверху.</span></div>
    {type === 'piles' ? <><div className="stats-row"><Stat label="Сваи дома" value={`${calculation.foundation.housePiles} шт`} /><Stat label="Сваи пристроек" value={`${calculation.foundation.platformPiles} шт`} /><Stat label="Общие сваи" value={`${calculation.foundation.sharedPiles} шт`} tone="accent" /><Stat label="Всего уникальных" value={`${calculation.foundation.totalPiles} шт`} /><Stat label="Обвязка" value={`${formatNumber(calculation.foundation.bindingLength)} м`} /><Stat label="Доска" value={`${formatNumber(calculation.foundation.boardVolume, 3)} м³`} /></div><Panel title="Параметры основания"><div className="form-grid three"><NumberField label="Предельный шаг свай" value={project.settings.piles.spacing} suffix="м" min={0.5} onChange={(value) => setSetting('piles', 'spacing', value)} /><NumberField label="Доска на 1 м обвязки" value={project.settings.piles.boardVolumePerMeter} suffix="м³" step={0.001} onChange={(value) => setSetting('piles', 'boardVolumePerMeter', value)} /><Toggle label="Включить в смету" checked={project.services.foundation} onChange={(value) => setService('foundation', value)} /></div></Panel><Panel title="Ведомость фундамента"><SectionResult calculation={calculation} sectionKey="foundation" /></Panel></> : null}
    {type === 'sip' ? <><div className="stats-row"><Stat label="Пол" value={`${formatNumber(calculation.metrics.roomArea)} м²`} /><Stat label="Наружные стены" value={`${formatNumber(calculation.metrics.exteriorWallNetArea)} м²`} /><Stat label="Потолок" value={`${formatNumber(calculation.metrics.roomArea)} м²`} /><Stat label="Перегородки" value={`${formatNumber(calculation.metrics.partitionNetArea)} м²`} /><Stat label="Проёмы" value={`${formatNumber(calculation.metrics.totalOpeningsArea)} м²`} /></div><Panel title="Панели и запас"><div className="form-grid four"><SelectField label="Панель пола" value={project.settings.sip.floorThickness} onChange={(value) => setSetting('sip', 'floorThickness', value)} options={['124', '174', '224'].map((value) => ({ value, label: `${value} мм` }))} /><SelectField label="Панель стен" value={project.settings.sip.wallThickness} onChange={(value) => setSetting('sip', 'wallThickness', value)} options={['124', '174', '224'].map((value) => ({ value, label: `${value} мм` }))} /><SelectField label="Панель потолка" value={project.settings.sip.ceilingThickness} onChange={(value) => setSetting('sip', 'ceilingThickness', value)} options={['124', '174', '224'].map((value) => ({ value, label: `${value} мм` }))} /><NumberField label="Дополнительный запас" value={project.settings.sip.wastePercent} suffix="%" step={1} onChange={(value) => setSetting('sip', 'wastePercent', value)} /></div><div className="toggle-grid"><Toggle label="СИП-пол" checked={project.services.sipFloor} onChange={(value) => setService('sipFloor', value)} /><Toggle label="Наружные стены" checked={project.services.sipWalls} onChange={(value) => setService('sipWalls', value)} /><Toggle label="СИП-потолок" checked={project.services.sipCeiling} onChange={(value) => setService('sipCeiling', value)} /><Toggle label="Перегородки" checked={project.services.partitions} onChange={(value) => setService('partitions', value)} /></div></Panel><Panel title="Раскрой"><div className="table-wrap"><table className="data-table"><thead><tr><th>Конструкция</th><th>Чистая площадь</th><th>Панели</th><th>Куплено</th><th>Остаток</th><th>Рез</th></tr></thead><tbody>{calculation.sip.cutting.map((row) => <tr key={row.key}><td>{row.label}</td><td>{formatNumber(row.area)} м²</td><td>{row.panels} шт</td><td>{formatNumber(row.purchasedArea)} м²</td><td>{formatNumber(row.offcutArea)} м²</td><td>{formatNumber(row.cutMeters)} м</td></tr>)}</tbody></table></div></Panel><Panel title="Ведомость СИП"><SectionResult calculation={calculation} sectionKey="sip" /></Panel></> : null}
    {type === 'roof' ? <><div className="stats-row"><Stat label="Основная кровля" value={`${formatNumber(calculation.roof.geometry?.totalSlopeArea)} м²`} /><Stat label="Холодная" value={`${formatNumber(calculation.roof.coldArea)} м²`} /><Stat label="Тёплая СИП" value={`${formatNumber(calculation.roof.warmArea)} м²`} /><Stat label="Всего" value={`${formatNumber(calculation.roof.totalArea)} м²`} tone="accent" /></div><Panel title="Основная крыша"><div className="form-grid four"><SelectField label="Тип" value={project.settings.roof.type} onChange={(value) => setSetting('roof', 'type', value)} options={[{ value: 'cold', label: 'Холодная' }, { value: 'sip', label: 'Тёплая СИП' }, { value: 'combo', label: 'Комбинированная' }]} /><NumberField label="Высота конька" value={project.settings.roof.ridgeHeight} suffix="м" onChange={(value) => setSetting('roof', 'ridgeHeight', value)} /><NumberField label="Длина конька" value={project.settings.roof.ridgeLength} suffix="м" onChange={(value) => setSetting('roof', 'ridgeLength', value)} /><NumberField label="Запас покрытия" value={project.settings.roof.wastePercent} suffix="%" step={1} onChange={(value) => setSetting('roof', 'wastePercent', value)} />{project.settings.roof.type === 'combo' ? <NumberField label="Тёплая часть" value={project.settings.roof.warmPercent} suffix="%" max={100} step={5} onChange={(value) => setSetting('roof', 'warmPercent', value)} /> : null}</div></Panel><Panel title="Кровли пристроек">{calculation.roof.terraceRoofs.map(({ platform, result }) => <div className="calculation-row" key={platform.id}><div><strong>{platform.kind === 'porch' ? 'Крыльцо' : 'Терраса'}</strong><span>{platform.roof.mode === 'none' ? 'без кровли' : platform.roof.mode === 'cold' ? 'холодная' : 'тёплая СИП'}</span></div><strong>{formatNumber(result.netArea)} м² <small>· с запасом {formatNumber(result.purchaseArea)} м²</small></strong></div>)}</Panel><Panel title="Ведомость кровли"><SectionResult calculation={calculation} sectionKey="roof" /></Panel></> : null}
    {type === 'terrace' ? <><div className="stats-row"><Stat label="Площадок" value={`${project.plan.platforms.length} шт`} /><Stat label="Площадь настила" value={`${formatNumber(calculation.terrace.area)} м²`} /><Stat label="Ступеней" value={`${project.plan.platforms.reduce((sum, item) => sum + (item.steps || 0), 0)} шт`} /><Stat label="Сваи пристроек" value={`${calculation.foundation.platformPiles} шт`} /></div><Panel title="Площадки проекта">{project.plan.platforms.map((platform) => { const result = calculateTerraceRoof(platform, project.plan.house); return <div className="calculation-row" key={platform.id}><div><strong>{platform.kind === 'porch' ? 'Крыльцо' : 'Терраса'} · {formatNumber(platform.w * platform.h)} м²</strong><span>{platform.foundation.mode === 'shared' ? 'общее свайное поле' : platform.foundation.mode === 'separate' ? 'отдельные сваи' : 'без свай'} · {platform.binding.mode === 'shared' ? 'общая обвязка' : platform.binding.mode === 'separate' ? 'отдельная обвязка' : 'без обвязки'}</span></div><strong>{platform.roof.mode === 'none' ? 'Без кровли' : `${formatNumber(result.netArea)} м² кровли`}</strong></div>; })}</Panel><Panel title="Ведомость террасы"><SectionResult calculation={calculation} sectionKey="terrace" /></Panel></> : null}
    {type === 'openings' ? <><div className="stats-row"><Stat label="Окна" value={`${project.plan.openings.filter((item) => item.type === 'window').length} шт`} /><Stat label="Двери" value={`${project.plan.openings.filter((item) => item.type === 'door').length} шт`} /><Stat label="Общая площадь" value={`${formatNumber(calculation.metrics.totalOpeningsArea)} м²`} /></div><Panel title="Проёмы с плана"><div className="calculation-list">{project.plan.openings.map((opening) => <div className="calculation-row" key={opening.id}><div><strong>{opening.type === 'window' ? 'Окно' : opening.doorType === 'interior' ? 'Межкомнатная дверь' : 'Входная дверь'}</strong><span>{Math.round(opening.width * 1000)} × {Math.round(opening.height * 1000)} мм</span></div><strong>{formatNumber(opening.width * opening.height, 2)} м²</strong></div>)}</div></Panel><Panel title="Ведомость проёмов"><SectionResult calculation={calculation} sectionKey="openings" /></Panel></> : null}
    {type === 'engineering' ? <><Panel title="Выбор инженерных систем"><div className="toggle-grid"><Toggle label="Электрика" checked={project.services.engineeringElectric} onChange={(value) => setService('engineeringElectric', value)} /><Toggle label="Водоснабжение" checked={project.services.engineeringPlumbing} onChange={(value) => setService('engineeringPlumbing', value)} /><Toggle label="Канализация" checked={project.services.engineeringSewerage} onChange={(value) => setService('engineeringSewerage', value)} /><Toggle label="Вентиляция" checked={project.services.engineeringVentilation} onChange={(value) => setService('engineeringVentilation', value)} /></div><div className="form-grid four"><NumberField label="Кабельные трассы" value={project.settings.engineering.cableRoute} suffix="м" onChange={(value) => setSetting('engineering', 'cableRoute', value)} /><NumberField label="Электроточки" value={project.settings.engineering.electricPoints} suffix="шт" step={1} onChange={(value) => setSetting('engineering', 'electricPoints', value)} /><NumberField label="Водопровод" value={project.settings.engineering.waterPipe} suffix="м" onChange={(value) => setSetting('engineering', 'waterPipe', value)} /><NumberField label="Точки воды" value={project.settings.engineering.waterPoints} suffix="шт" step={1} onChange={(value) => setSetting('engineering', 'waterPoints', value)} /><NumberField label="Канализация" value={project.settings.engineering.sewerLength} suffix="м" onChange={(value) => setSetting('engineering', 'sewerLength', value)} /><NumberField label="Точки канализации" value={project.settings.engineering.sewerPoints} suffix="шт" step={1} onChange={(value) => setSetting('engineering', 'sewerPoints', value)} /><NumberField label="Воздуховоды" value={project.settings.engineering.ventDuct} suffix="м" onChange={(value) => setSetting('engineering', 'ventDuct', value)} /><NumberField label="Решётки" value={project.settings.engineering.ventGrilles} suffix="шт" step={1} onChange={(value) => setSetting('engineering', 'ventGrilles', value)} /></div></Panel><Panel title="Ведомость инженерии"><SectionResult calculation={calculation} sectionKey="engineering" /></Panel></> : null}
    {type === 'finishing' ? <><div className="two-column-layout"><Panel title="Внутренняя отделка"><Toggle label="Включить раздел" checked={project.services.internalFinish} onChange={(value) => setService('internalFinish', value)} /><div className="form-grid"><NumberField label="Стены" value={project.settings.internal.wallArea} suffix="м²" onChange={(value) => setSetting('internal', 'wallArea', value)} /><NumberField label="Потолок" value={project.settings.internal.ceilingArea} suffix="м²" onChange={(value) => setSetting('internal', 'ceilingArea', value)} /><NumberField label="Ламинат" value={project.settings.internal.laminateArea} suffix="м²" onChange={(value) => setSetting('internal', 'laminateArea', value)} /><NumberField label="Плитка" value={project.settings.internal.tileArea} suffix="м²" onChange={(value) => setSetting('internal', 'tileArea', value)} /><NumberField label="Двери" value={project.settings.internal.doors} suffix="шт" step={1} onChange={(value) => setSetting('internal', 'doors', value)} /></div></Panel><Panel title="Наружная отделка"><Toggle label="Включить раздел" checked={project.services.externalFinish} onChange={(value) => setService('externalFinish', value)} /><div className="form-grid"><NumberField label="Фасад" value={project.settings.external.facadeArea} suffix="м²" onChange={(value) => setSetting('external', 'facadeArea', value)} /><NumberField label="Ветрозащита" value={project.settings.external.windArea} suffix="м²" onChange={(value) => setSetting('external', 'windArea', value)} /><NumberField label="Утепление" value={project.settings.external.insulationArea} suffix="м²" onChange={(value) => setSetting('external', 'insulationArea', value)} /><NumberField label="Профлист" value={project.settings.external.metalArea} suffix="м²" onChange={(value) => setSetting('external', 'metalArea', value)} /><NumberField label="Подшива" value={project.settings.external.soffitArea} suffix="м²" onChange={(value) => setSetting('external', 'soffitArea', value)} /></div></Panel></div><Panel title="Внутренняя ведомость"><SectionResult calculation={calculation} sectionKey="internal" /></Panel><Panel title="Наружная ведомость"><SectionResult calculation={calculation} sectionKey="external" /></Panel></> : null}
    {type === 'delivery' ? <><Panel title="Логистика"><div className="form-grid four"><NumberField label="Расстояние" value={project.settings.delivery.distance} suffix="км" onChange={(value) => setSetting('delivery', 'distance', value)} /><NumberField label="Количество рейсов" value={project.settings.delivery.trips} suffix="рейс" step={1} onChange={(value) => setSetting('delivery', 'trips', value)} /><NumberField label="Объём груза" value={project.settings.delivery.cargoVolume} suffix="м³" onChange={(value) => setSetting('delivery', 'cargoVolume', value)} /><NumberField label="База рейса" value={project.settings.delivery.baseTrip} suffix="₽" step={100} onChange={(value) => setSetting('delivery', 'baseTrip', value)} /><NumberField label="Цена километра" value={project.settings.delivery.perKm} suffix="₽" step={1} onChange={(value) => setSetting('delivery', 'perKm', value)} /><NumberField label="Разгрузка" value={project.settings.delivery.unloadingPerM3} suffix="₽/м³" step={10} onChange={(value) => setSetting('delivery', 'unloadingPerM3', value)} /></div></Panel><Panel title="Ведомость доставки"><SectionResult calculation={calculation} sectionKey="delivery" /></Panel></> : null}
  </div>;
}
