import ProductionView from '../components/ProductionView.jsx';
import { PrintPlanDiagram } from '../components/PrintProjectDiagrams.jsx';
import { TechnicalDrawing } from './MountingAlbum.jsx';
import { StructuralPlan,RoofSection } from './RoofDrawings.jsx';
import ConstructionNode from './ConstructionNodes.jsx';
import { groupStockMaps } from '../calculations/project-release.js';
import { polygonBounds } from '../calculations/production-cutting.js';
const chunks=(rows,n)=>Array.from({length:Math.ceil(rows.length/n)},(_,i)=>rows.slice(i*n,i*n+n));
const layers={shell:['walls','gables','roof','binding'],inside:['walls','partitions','floor','binding','supports'],roof:['roof','supports'],base:['binding','supports']};
const materialName=value=>({pps:'СИП · ППС',pu:'СИП · ППУ',mw:'СИП · минвата'}[value]||value);
const Table=({head,rows,className=''})=><table className={`release-table ${className}`}><thead><tr>{head.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v??'—'}</td>)}</tr>)}</tbody></table>;
const Panel=({title,children})=><section className="release-visual-panel"><h3>{title}</h3>{children}</section>;
function PartDrawing({part}){const box=polygonBounds(part.shape);const local={...part,x:0,y:0,shape:part.shape.map(r=>r.map(([x,y])=>[x-box.x,y-box.y]))};return <TechnicalDrawing surface={{id:part.displayMark,horizontal:true,width:part.width,height:part.height,geometry:[local.shape]}} parts={[local]} fontScale={2.2}/>;}
function BarDrawing({bar,length}){return <svg className="release-stock-bar" viewBox={`0 0 ${length} 300`} role="img" aria-label={`Раскрой ${bar.id}, заготовка ${length} мм`}><rect width={length} height="250" fill="#eee" stroke="#555" strokeWidth=".5" vectorEffect="non-scaling-stroke"/>{bar.parts.map(p=><g key={p.id}><rect x={p.start} width={p.length} height="250" fill="#e4ceb0" stroke="#333" strokeWidth=".5" vectorEffect="non-scaling-stroke"/><title>{p.displayMark||p.id} · {p.length} мм · начало {p.start} мм</title>{p.length>650?<text x={p.start+p.length/2} y="175" textAnchor="middle" fontSize="170">{p.displayMark||p.id} · {p.length}</text>:null}</g>)}</svg>;}

export function compactReleasePages(release){
  const {project,report,registers}=release,pages=[];
  const add=(group,title,content,info={})=>{const id=`${group}${String(pages.filter(p=>p.group===group).length+1).padStart(2,'0')}`;pages.push({id,group,title,content,scale:'не в масштабе',units:'мм; м²; м³',direction:'сверху / аксонометрия / локальный вид по подписи',axes:'Проектные оси не назначены',layout:'visual-v2',...info});};
  const view=(props={})=><ProductionView report={report} project={project} {...props}/>;
  add('ОБ','Домокомплект · общий вид и состав',<><div className="release-cover"><div>{view({layers:layers.shell,title:'Общий вид · панели и кровельный каркас'})}</div><div><h1>{project.meta.projectName||'Домокомплект SIP'}</h1><p>{project.meta.address||'Адрес не указан'}</p><Table head={['Параметр','Значение']} rows={[
    ['Габарит, м',`${project.plan.house.w} × ${project.plan.house.h}`],['Этажей',report.assembly.floors.length],['Панелей / деревянных деталей',`${report.parts.length} / ${report.members.filter(m=>!m.excluded).length}`],['Заготовка панели, мм',`${report.panelLength} × ${report.panelWidth}`],['Смета, ₽',new Intl.NumberFormat('ru-RU').format(release.calculation.totals.total)],['Резы панели / дерево',`${report.cutting.panelCuts} / ${report.cutting.timberCuts}`],['Открытых проверок',release.validation.blocks.length]]}/><p>ЧЕРНОВИК. Узлы и несущая способность требуют подтверждения. Полные ведомости, остатки, цены и проверки — в машинном комплекте и подробном приложении.</p><div className="release-cover-frame">{view({frame:true,title:'Каркас домокомплекта · без обшивок'})}</div></div></div><nav className="release-inline-index">{['ОБ · Общий вид','АР · Планы','КД · Конструкции','ПР · Детали и раскрой','ВП · Проверки'].join(' / ')}</nav></>);
  for(const [i,floor]of report.assembly.floors.entries()){
    const plan=i===0?project.plan:project.upperFloors[i-1];
    add('АР',`Этаж ${floor.floor} · план и объёмная схема`,<div className="release-visual-grid"><Panel title="План помещений и проёмов"><PrintPlanDiagram plan={plan} pileSettings={project.settings.piles} options={{showPiles:false,showBinding:false,showRoof:false,showRooms:true,showOpenings:true,showDimensions:true}} floorOpening={i===0?project.upperFloors[0]?.floorOpenings:plan.floorOpenings}/></Panel><Panel title="Без кровли и потолка">{view({layers:layers.inside,floor:floor.floor,title:`Этаж ${floor.floor} · размещение панелей и каркаса`})}<p>Высота стен: {plan.wallHeight} м. Проёмы и помещения подписаны на плане.</p></Panel></div>,{direction:'сверху; объёмный вид без кровли'});
  }
  if(report.assembly.piles.length)add('КД','Основание и обвязка',<div className="release-visual-grid"><Panel title="Опоры, линии обвязки, контрольные размеры"><StructuralPlan assembly={report.assembly} kind="binding"/></Panel><div className="release-stacked"><Panel title="Пространственная схема обвязки">{view({layers:layers.base,title:'Обвязка и проектные опоры'})}</Panel><Panel title="Н1 · сопряжение"><ConstructionNode type="base" report={report}/></Panel></div></div>);
  for(const [i,list]of chunks(report.surfaces.filter(s=>s.geometry?.length),2).entries())add('КД',`Развёртки и раскладки · ${i+1}`,<div className="release-visual-grid release-surface-grid">{list.map(s=>{const parts=report.parts.filter(p=>p.surfaceId===s.id),members=report.members.filter(m=>m.surfaceId===s.id&&!m.excluded);return <Panel key={s.id} title={`${s.id} · ${s.name}`}><TechnicalDrawing surface={s} parts={parts} members={members}/><div className="release-surface-view">{view({surfaceIds:[s.id],title:'Панели и соединители · объёмный вид'})}</div><p>{parts.length} панелей · {members.length} деревянных деталей{s.blocked?' · РАСКЛАДКА ЗАБЛОКИРОВАНА':''}. Марки — в ведомостях ПР.</p></Panel>;})}</div>,{surfaceIds:list.map(s=>s.id)});
  if(report.assembly.rafters.length)add('КД','Кровля · план, профиль и 3D каркас',<div className="release-roof-grid release-roof-sheet"><Panel title="Стропильный план"><StructuralPlan assembly={report.assembly}/></Panel><Panel title="Каркас кровли">{view({layers:layers.roof,frame:true,title:'Стропила, прогоны и опоры'})}</Panel><Panel title="Поперечный профиль и длины"><RoofSection assembly={report.assembly}/></Panel><Panel title="Н4 · опирание"><ConstructionNode type="roof" report={report} compact/></Panel></div>);
  const frameSurface=report.surfaces.find(s=>s.partitionFrame);
  add('КД','Узлы стен и перегородок',<div className="release-roof-grid"><Panel title="Н2 · угол SIP"><ConstructionNode type="corner" report={report}/></Panel><Panel title="Объёмная схема каркаса">{view({layers:layers.inside,frame:true,title:'Каркас без обшивок'})}</Panel>{frameSurface?<><Panel title="Н3 · примыкание"><ConstructionNode type="partition" report={report} surface={frameSurface}/></Panel><Panel title="Н5 · несущая перегородка"><ConstructionNode type="bearing" report={report} surface={report.surfaces.find(s=>s.partitionFrame&&s.bearing)||frameSurface}/></Panel></>:null}</div>);
  for(const [i,list]of chunks(registers.panels,6).entries())add('ПР',`Панели · типоразмеры и количество · ${i+1}`,<div className="release-detail-grid">{list.map(r=>{const p=report.parts.find(p=>p.id===r.ids[0]);return <Panel key={r.mark} title={`${r.mark} · ×${r.qty}`}><PartDrawing part={p}/><p>{materialName(r.material)} · {r.size} мм</p></Panel>;})}</div>);
  for(const [i,list]of chunks(registers.timber,22).entries())add('ПР',`Деревянные детали · ${i+1}`,<Table head={['Марка','Материал','Размер / сечение и длина, мм','Кол.','Обработка']} rows={list.map(r=>[r.mark,r.material,r.size,`×${r.qty}`,r.processing])}/>);
  for(const [i,list]of chunks(groupStockMaps(report.panelStock.sheets,'panel'),6).entries())add('ПР',`Карты раскроя панелей · ${i+1}`,<div className="release-detail-grid">{list.map(({item:s,qty})=><Panel key={s.id} title={`${s.id} · ×${qty}`}><TechnicalDrawing surface={{id:s.id,horizontal:true,geometry:[[[[0,0],[s.width,0],[s.width,s.height],[0,s.height],[0,0]]]]}} parts={s.parts.map(p=>({...p,shape:[[[p.x,p.y],[p.x+p.width,p.y],[p.x+p.width,p.y+p.height],[p.x,p.y+p.height],[p.x,p.y]]],displayMark:report.parts.find(r=>r.id===p.id)?.displayMark}))}/><p>{s.width}×{s.height} мм · пропил {report.settings.kerfMm} мм</p></Panel>)}</div>);
  for(const [i,list]of chunks(groupStockMaps(report.timberStock.bars,'timber'),18).entries())add('ПР',`Раскрой пиломатериала · ${i+1}`,<Table className="release-stock-table" head={['Заготовка','Материал / сечение','Карта раскроя · марки и размеры, мм']} rows={list.map(({item:b,qty})=>[`${b.id} · ×${qty}`,`${b.material} ${b.profile}`,<div key={b.id}><BarDrawing bar={b} length={report.settings.stockLengthMm}/><small>{b.parts.map(p=>`${p.displayMark||p.id}: ${p.start} / ${p.length}`).join('; ')}</small></div>])}/>);
  for(const [i,list]of chunks(report.reconciliation,16).entries())add('ВП',`Сверка комплектации · ${i+1}`,<><Table head={['Материал','Ед.','Производство','Смета','Разница']} rows={list.map(r=>[r.name,r.unit,r.required,r.purchased??'не сопоставлено',r.difference??'—'])}/><p>Недостача не закрывается примечанием. Каталог, цены, упаковка и остатки — в ZIP; это не замена закупочной ведомости.</p></>);
  const checks=new Map();for(const b of release.validation.blocks){const rows=checks.get(b.code)||[];rows.push(b);checks.set(b.code,rows);}
  if(checks.size)add('ВП','Контроль выпуска · сводная карта',<><Table head={['Проверка','Количество','Примеры причин','Где исправить']} rows={[...checks].map(([code,rows])=>[code,rows.length,rows.slice(0,2).map(b=>b.message).join('; ')+(rows.length>2?` · ещё ${rows.length-2}, см. полный реестр`:''),[...new Set(rows.map(b=>b.path))].join('; ')])}/><p>Все {release.validation.blocks.length} причин сохранены без сокращения в снимке JSON и подробном приложении. Эта карта группирует их только для компактной печати; разрешение производства не меняется.</p><div className="release-check-view">{view({frame:true,yaw:145,title:'Контрольная схема каркаса · обратный ракурс'})}</div></>);
  return pages;
}
