import Dimensions from '../components/DrawingDimensions.jsx';

// Project-dependent geometry, not a prescribed fastener or structural design.
export default function ConstructionNode({type,report,surface}) {
  const sip=report.surfaces.find(s=>s.id==='Э1-С1')?.thickness||surface?.thickness||174;
  const b=report.assembly.binding[0],profile=surface?.frameProfile||b?.profile||'',values=profile.split(/[×xх]/).map(Number),t=values[0]||50,d=values[1]||100;
  const kind=type==='base'?'Н1':type==='corner'?'Н2':type==='partition'?'Н3':type==='roof'?'Н4':'Н5';
  const title={base:'Основание → обвязка → перекрытие → стена',corner:'Сопряжение наружных СИП-стен · вид сверху',partition:'Угол / Т-примыкание перегородок',roof:'Стропило → мауэрлат → несущая стена',bearing:'Доска на ребре под верхней обвязкой'}[type];
  return <section className="construction-node"><h3>{kind} · {title}</h3>
    <svg viewBox="-35 -35 550 420" role="img" aria-label={`${kind} · ${title}`}>
      {type==='corner'?<><path d={`M0,0H390V${sip}H${sip}V320H0Z`} fill="#eef3e8" stroke="#000" strokeWidth=".7"/><path d={`M0,0V${sip}H390 M${sip},${sip}H0`} fill="none" stroke="#000" strokeWidth=".7"/><rect x="0" y={sip} width={sip} height="28" fill="#e9d6b7" stroke="#000" strokeWidth=".7"/><text x={sip+20} y={sip+50} fontSize="14">Примыкающая стена</text><text x="190" y="-15" fontSize="14">Проходная стена</text><Dimensions values={[0,sip]} y={345} font={14}/><text x="200" y="320" fontSize="13">Торец / соединитель: по узлу проекта</text></>:null}
      {type==='base'?<><rect x="30" y="255" width="150" height="60" fill="#eee" stroke="#000" strokeWidth=".7"/><rect x="30" y="170" width="150" height="80" fill="#eedbbb" stroke="#000" strokeWidth=".7"/>{Array.from({length:b?.layers||1},(_,i)=><line key={i} x1={30+150*i/(b?.layers||1)} y1="170" x2={30+150*i/(b?.layers||1)} y2="250" stroke="#000" strokeWidth=".7"/>)}<line x1="20" y1="254" x2="190" y2="254" stroke="#000" strokeWidth="2"/><rect x="30" y="110" width="300" height="60" fill="#edf3e7" stroke="#000" strokeWidth=".7"/><rect x="30" y="0" width="60" height="110" fill="#edf3e7" stroke="#000" strokeWidth=".7"/><text x="195" y="205" fontSize="14">{b?`${b.layers} × ${b.profile} мм`:'Обвязка по проекту'}</text><text x="195" y="280" fontSize="14">{report.assembly.foundationType==='concreteBlock'?'Бетонный блок':'Свая / оголовок'}</text><text x="195" y="310" fontSize="13">Габариты опоры — в настройках</text><text x="100" y="45" fontSize="14">Стена {sip} мм</text><text x="340" y="140" fontSize="13">СИП-пол</text><text x="195" y="245" fontSize="13">Разделительный слой — по узлу</text></>:null}
      {type==='partition'?<><rect x="0" y="0" width="400" height={d} fill="#faf5eb" stroke="#000" strokeWidth=".7"/><rect x="180" y={d} width={d} height="220" fill="#faf5eb" stroke="#000" strokeWidth=".7"/>{[0,180,180+d,400-t].map(x=><rect key={x} x={x} y="0" width={t} height={d} fill="#ead5b1" stroke="#000" strokeWidth=".7"/>)}<rect x="180" y={d} width={d} height={t} fill="#ead5b1" stroke="#000" strokeWidth=".7"/><text x="290" y={d+80} fontSize="14">Закладные под листы</text><text x="290" y={d+100} fontSize="13">с обеих сторон стыка</text><Dimensions values={[0,d]} y="350" font={14}/><text x="20" y="-15" fontSize="14">Каркас {profile} мм · расположение по узлу</text></>:null}
      {type==='bearing'?<><rect x="0" y="0" width="400" height={t*2} fill="#e9d6b7" stroke="#000" strokeWidth=".7"/><rect x="0" y={t*2} width="400" height={d} fill="#e9d6b7" stroke="#000" strokeWidth=".7"/>{[0,175,350].map(x=><rect key={x} x={x} y={t*2} width={t} height="260" fill="none" stroke="#000" strokeWidth=".7"/>)}<text x="20" y="-15" fontSize="14">Верхняя обвязка · доска {profile}</text><text x="60" y={t*2+d/2} fontSize="14">Доска {profile} на ребре</text><text x="70" y="335" fontSize="13">Врезка: глубина и допустимость — по проекту</text></>:null}
      {type==='roof'?<><rect x="70" y="205" width="75" height="140" fill="#edf3e7" stroke="#000" strokeWidth=".7"/><rect x="60" y="155" width="100" height="50" fill="#e9d6b7" stroke="#000" strokeWidth=".7"/><path d="M0,185L370,20L390,65L20,230Z" fill="#e9d6b7" stroke="#000" strokeWidth=".7"/><circle cx="100" cy="170" r="28" fill="none" stroke="#000" strokeDasharray="4 3"/><text x="185" y="170" fontSize="14">Мауэрлат {report.assembly.roofTimbers?.find(m=>/Мауэрлат/.test(m.material))?.profile||'по проекту'}</text><text x="185" y="195" fontSize="13">Крепёж / врубка — не назначены</text><text x="175" y="280" fontSize="14">Стена → балка → обвязка → опора</text><text x="175" y="305" fontSize="13">Путь нагрузки проверить в плане опор</text><text x="5" y="-10" fontSize="14">Стропило {report.assembly.rafters[0]?.profile||'по проекту'}</text></>:null}
    </svg><p>Схема сопряжения, не масштабный рабочий узел. Размеры и сечения — из проекта. Крепёж, врезки, гидроизоляция и допустимые нагрузки требуют подтверждения. {type==='base'?'Образец состава: «Мичуринец», лист 5 / PDF 5.':type==='roof'?'Образец состава: «Мичуринец», листы 18, 20 / PDF 18, 20.':type==='partition'||type==='bearing'?'Курмановы: печатные стр. 93–94 / PDF 94–95; нормы источника не заменяют параметры EFT.':''}</p>
  </section>;
}
