import { useEffect, useMemo, useState } from 'react';
import { createPortal, flushSync } from 'react-dom';
import { Printer, Plus, Trash2 } from 'lucide-react';
import { useProject } from '../state/ProjectContext.jsx';
import { normalizeProductionCutting } from '../state/production-cutting.js';
import { polygonBounds, groupPanels, groupMembers } from '../calculations/production-cutting.js';
import { SIP_GUIDE_ENTRIES } from '../data/sip-guide.js';
import '../styles/cutting.css';
import { approvalLabels, CuttingControls, SurfaceLayoutControls, MemberEditor, Reconciliation, DraftText } from './CuttingControls.jsx';
import AssemblyPlan, { AssemblyDiagram } from './AssemblyPlan.jsx';
import { productionMark as mark, productionFamily } from '../calculations/production-assembly.js';
import { PRODUCTION_GUIDANCE } from '../data/production-guidance.js';
import MountingAlbum from './MountingAlbum.jsx';
import DrawingWorkbench from './DrawingWorkbench.jsx';

const formatter = new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 3 });
const n = value => formatter.format(Number(value) || 0);
const pathFor = (shape, flipY) => shape.map(ring => ring.map((p, i) => `${i ? 'L' : 'M'}${p[0]},${flipY == null ? p[1] : flipY - p[1]}`).join(' ') + 'Z').join(' ');
const sources = SIP_GUIDE_ENTRIES.filter(entry => ['sip-floor-ceiling-fasteners', 'sip-openings', 'sip-seam-screws', 'sip-roof'].includes(entry.id));

function NumberInput({ label, value, onChange, placeholder = 'Введите значение, мм', min = 0, max = 100000, suffix = 'мм' }) {
  const [draft, setDraft] = useState(value ?? '');
  const [error, setError] = useState('');
  useEffect(() => setDraft(value ?? ''), [value]);
  return <label>{label}<span className="cut-input"><input aria-label={label} aria-invalid={!!error} type="number" min={min} max={max} step="any" value={draft} placeholder={placeholder} onChange={event => { setDraft(event.target.value); setError(''); }} onBlur={() => { if (draft !== '' && (!Number.isFinite(Number(draft)) || Number(draft)<min || Number(draft)>max || (suffix === 'шт.' && !Number.isInteger(Number(draft))))) { setError(`Не сохранено: введите ${suffix === 'шт.' ? 'целое ' : ''}от ${min} до ${max}`); return; } if (String(draft) !== String(value ?? '')) onChange(draft); }} onKeyDown={event => { if (event.key === 'Enter') event.currentTarget.blur(); }} /><small>{suffix}</small></span>{error ? <small role="alert">{error}</small> : null}</label>;
}

function Layout({ surface, parts, selected, onSelect, members = [], onMemberSelect }) {
  if (!surface?.geometry?.length) return <p className="cut-empty">Контур отсутствует. Добавьте геометрию на плане.</p>;
  const bounds = polygonBounds(surface.geometry.flat()), pad = Math.max(bounds.width, bounds.height) * 0.055;
  const flip = surface.horizontal ? null : bounds.y * 2 + bounds.height;
  return <svg className="cut-layout" viewBox={`${bounds.x - pad} ${bounds.y - pad} ${bounds.width + 2 * pad} ${bounds.height + 2 * pad}`} role="img" aria-label={`Раскладка: ${surface.name}`}>
    {surface.planStart ? <text x={bounds.x + bounds.width / 2} y={bounds.y - pad * 0.35} textAnchor="middle" fontSize={pad * 0.26}>На плане, мм: ({surface.planStart.map(n).join('; ')}) → ({surface.planEnd.map(n).join('; ')})</text> : null}
    {surface.geometry.map((shape, i) => <path key={i} d={pathFor(shape, flip)} fill="#f6f7ef" stroke="#88917c" strokeWidth="1" vectorEffect="non-scaling-stroke" fillRule="evenodd" />)}
    {parts.map(part => <g key={part.id} role={onSelect ? 'button' : undefined} tabIndex={onSelect ? 0 : undefined} aria-label={`Деталь ${mark(part)}, ${n(part.width)} на ${n(part.height)} мм`} onClick={() => onSelect?.(part.id)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onSelect?.(part.id); } }}>
      <path d={pathFor(part.shape, flip)} fill={selected === part.id ? '#92ba67' : part.upperCourse ? '#f0d6a1' : '#deead1'} stroke="#517239" strokeWidth="1" vectorEffect="non-scaling-stroke" fillRule="evenodd" />
      <text x={part.x + part.width / 2} y={flip == null ? part.y + part.height / 2 : flip - part.y - part.height / 2} textAnchor="middle" dominantBaseline="middle" fontSize={Math.min(part.width * 0.12, bounds.width * 0.018)}>{mark(part).replace(`${mark(surface.id)}-`, '')}</text>
      <title>{mark(part)}: {n(part.width)} × {n(part.height)} × {part.thickness} мм</title>
    </g>)}
    {members.filter(m=>['jamb','frame'].includes(m.role)&&m.a&&!m.excluded).map(m=><line key={`line-${m.id}`} x1={m.a[0]} y1={flip==null?m.a[1]:flip-m.a[1]} x2={m.b[0]} y2={flip==null?m.b[1]:flip-m.b[1]} stroke="#8d4b26" strokeWidth="4" vectorEffect="non-scaling-stroke"/>)}
    {members.filter(m=>m.a && !m.excluded).map(member=><g key={member.id} role={onMemberSelect ? 'button' : undefined} tabIndex={onMemberSelect ? 0 : undefined} aria-label={`Соединитель ${mark(member)}`} onClick={()=>onMemberSelect?.(member.key)} onKeyDown={e=>{if(e.key==='Enter')onMemberSelect?.(member.key);}}><circle cx={(member.a[0]+member.b[0])/2} cy={flip == null ? (member.a[1]+member.b[1])/2 : flip-(member.a[1]+member.b[1])/2} r={Math.max(bounds.width*.004,3)} fill="#ae5833"/><title>{mark(member)} · {member.profile} · {member.length} мм</title><text x={(member.a[0]+member.b[0])/2} y={(flip == null ? (member.a[1]+member.b[1])/2 : flip-(member.a[1]+member.b[1])/2)-bounds.width*.006} textAnchor="middle" fontSize={bounds.width*.012}>{mark(member).replace(`${mark(surface.id)}-`,'')}</text></g>)}
    <text x={bounds.x + bounds.width / 2} y={bounds.y + bounds.height + pad * 0.75} textAnchor="middle" fontSize={pad * 0.32}>{n(bounds.width)} мм</text>
    <text x={bounds.x - pad * 0.35} y={bounds.y + bounds.height / 2} textAnchor="middle" fontSize={pad * 0.32} transform={`rotate(-90 ${bounds.x - pad * 0.35} ${bounds.y + bounds.height / 2})`}>{n(bounds.height)} мм</text>
  </svg>;
}

function PanelTable({ parts, onSelect }) {
  return <div className="cut-table-wrap"><table><thead><tr><th>Марка / одинаковые детали</th><th>Количество</th><th>Габарит детали / заготовка Ш × Д, мм</th><th>Толщина</th><th>Площадь одной, м²</th><th>Позиции на плане</th></tr></thead><tbody>{groupPanels(parts).map(({part,qty,instances}) => <tr key={part.id}><td>{onSelect ? <button onClick={() => onSelect(part.id)}>{mark(part)}</button> : mark(part)}{part.upperCourse ? ' · добор' : ''}</td><td><strong className="cut-quantity">×{qty}</strong></td><td>{n(part.width)} × {n(part.height)}<small>Заготовка: {Math.ceil(part.blankWidth ?? part.width)} × {Math.ceil(part.blankHeight ?? part.height)}</small></td><td>{part.thickness}</td><td>{n(part.area / 1e6)}</td><td><small>{instances.map(mark).join(', ')}</small></td></tr>)}</tbody></table></div>;
}

function MemberTable({ members, onSelect }) {
  return <div className="cut-table-wrap"><table><thead><tr><th>Марка / одинаковые элементы</th><th>Количество</th><th>Элемент / узел</th><th>Сечение, мм</th><th>Чистая / заготовка, мм</th><th>Позиции и привязка</th></tr></thead><tbody>{groupMembers(members).map(({member,qty,instances}) => <tr key={member.id}><td>{onSelect && member.key ? <button onClick={()=>onSelect(member.key)}>{mark(member)}</button> : mark(member)}<small>{member.surface}{member.excluded ? ' · ИСКЛЮЧЁН ИЗ ХЛЫСТОВ' : ''}</small></td><td><strong className="cut-quantity">×{qty}</strong></td><td>{member.material}<small>{member.source}</small><small>{member.nodeRef || 'Узел не задан'} · {member.processing || 'Обработка по альбому узлов'}</small></td><td>{member.profile}</td><td>{n(member.length)} / {n(member.cutLength)}</td><td><small>{instances.map(item=>mark(item)).join(', ')}</small>{onSelect ? <details><summary>Открыть позиции</summary>{instances.map(item=><p key={item.id}>{item.key ? <button onClick={()=>onSelect(item.key)}>{mark(item)}</button> : mark(item)} · {item.openingRef || item.surface} {item.a ? `(${item.a.map(n).join('; ')}) → (${item.b.map(n).join('; ')}) мм` : ''}</p>)}</details> : <small>{instances.map(item=>item.openingRef || item.surface).join('; ')}</small>}</td></tr>)}</tbody></table></div>;
}

function StarterBoardDiagram({ walls = [] }) {
  if (!walls.length) return <p className="cut-empty">Стартовая доска не сформирована: включите наружные SIP-стены и проверьте контур.</p>;
  const points=walls.flatMap(wall=>[wall.start,wall.end]);
  const xs=points.map(point=>point[0]),ys=points.map(point=>point[1]);
  const x=Math.min(...xs),y=Math.min(...ys),width=Math.max(...xs)-x,height=Math.max(...ys)-y;
  const pad=Math.max(width,height)*.12;
  const font=Math.max(140,Math.min(240,Math.max(width,height)*.017));
  const at=(wall,distance)=>{const t=wall.length ? distance/wall.length : 0;return [wall.start[0]+(wall.end[0]-wall.start[0])*t,wall.start[1]+(wall.end[1]-wall.start[1])*t];};
  const line=(wall,start,end,key,kind)=>{const a=at(wall,start),b=at(wall,end);return <line key={key} x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} className={kind} vectorEffect="non-scaling-stroke" />;};
  const label=(wall,start,end,text,key,kind)=>{const [cx,cy]=at(wall,(start+end)/2);const dx=wall.end[0]-wall.start[0],dy=wall.end[1]-wall.start[1],length=Math.hypot(dx,dy)||1;return <text key={key} x={cx-dy/length*font*.85} y={cy+dx/length*font*.85} className={kind} textAnchor="middle" fontSize={font}>{text}</text>;};
  return <div className="cut-starter"><svg viewBox={`${x-pad} ${y-pad} ${width+2*pad} ${height+2*pad}`} role="img" aria-label="Монтаж стартовой торцевой доски, вид сверху">
    {walls.map(wall=><g key={wall.id}>
      {line(wall,0,wall.length,`${wall.id}-base`,'starter-wall')}
      {wall.boards.map(board=>line(wall,board.start,board.end,board.id,'starter-board'))}
      {wall.openings.filter(opening=>opening.noBoard).map(opening=>line(wall,opening.start,opening.end,`${opening.id}-gap`,'starter-gap'))}
      {label(wall,0,wall.length,`${n(wall.length)} мм`,`${wall.id}-length`,'starter-length')}
      {wall.openings.map(opening=>label(wall,opening.start,opening.end,`${opening.noBoard?'ПРОЁМ':'ОКНО'} ${n(opening.width)}`,`${opening.id}-label`,'starter-opening-label'))}
    </g>)}
  </svg><div className="cut-starter-legend"><span>Зелёный — доска</span><span>Красный — разрыв у пола</span><span>Окно выше пола — доска непрерывна</span></div>
  <div className="cut-table-wrap"><table><thead><tr><th>Стена</th><th>Длина, мм</th><th>Стартовая доска · марка, от–до, длина</th><th>Проёмы от начала стены</th></tr></thead><tbody>{walls.map(wall=><tr key={wall.id}><td>{wall.name}</td><td>{n(wall.length)}</td><td>{wall.boards.map(board=><div key={mark(board.id)}>{mark(board.id)}: {n(board.start)}–{n(board.end)} · {n(board.length)} мм · {board.profile}</div>)}</td><td>{wall.openings.map(opening=><div key={opening.id}>{opening.name}: {n(opening.start)}–{n(opening.end)} · {n(opening.width)} мм · {opening.noBoard?'без доски':'доска продолжается'}</div>)}</td></tr>)}</tbody></table></div></div>;
}

function StockSheets({ report }) {
  return <div className="cut-stock-grid">{report.panelStock.sheets.map(sheet => <article key={sheet.id} className="cut-stock"><h3>{sheet.id} · {sheet.thickness} мм · {productionFamily(sheet.family)}</h3><p>{n(sheet.width)} × {n(sheet.height)} мм</p><svg viewBox={`-30 -30 ${sheet.width + 60} ${sheet.height + 60}`} role="img" aria-label={`Карта заготовки ${sheet.id}`}><rect width={sheet.width} height={sheet.height} fill="#f7f4e9" stroke="#859471" />{sheet.parts.map(part => <g key={part.id}><rect x={part.x} y={part.y} width={part.width} height={part.height} fill="#dbe8d1" stroke="#54713c" strokeWidth="1" vectorEffect="non-scaling-stroke" /><text x={part.x + part.width / 2} y={part.y + part.height / 2} fontSize="35" textAnchor="middle">{mark(part)}{part.rotated ? ' ↻90°' : ''}</text></g>)}</svg><small>{sheet.parts.map(part => `${mark(part)}: X ${n(part.x)}, Y ${n(part.y)}, ${n(part.width)}×${n(part.height)}${part.rotated ? ' · поворот 90°' : ''}`).join('; ')}</small></article>)}</div>;
}

function PrintReport({ project, report, scope }) {
  if(scope==='album')return <MountingAlbum project={project} report={report}/>;
  const surfaces = scope === 'all' ? report.surfaces : report.surfaces.filter(s => s.id === scope);
  const members = scope === 'all' ? report.members : report.members.filter(m => m.surfaceId === scope);
  return <div className="production-print">
    <h1>ЭФТ · Раскрой домокомплекта</h1><p>Проект № {project.meta.projectNum || 'Не задан'} · {project.meta.customer || 'Заказчик не указан'} · {project.meta.address || 'Адрес не указан'}</p>
    <p>Ревизия {report.revision} · {approvalLabels[report.approvalStatus]}. Проверил: {report.settings.approval.reviewer || 'не указан'} · Альбом: {report.settings.approval.nodeRef || 'не указан'}</p>
    <p>{new Date().toLocaleDateString('ru-RU')} · {scope === 'all' ? 'Полный комплект' : 'Выбранная конструкция'} · Все размеры в мм. Шаг каркаса {n(report.settings.frameStepMm)}. Пропил: {report.settings.kerfMm === '' ? 'НЕ ЗАДАН' : n(report.settings.kerfMm)}. Припуск на торец: {report.settings.endAllowanceMm === '' ? 'НЕ ЗАДАН' : n(report.settings.endAllowanceMm)}.</p>
    <h2>{report.issues.length ? 'Предварительный комплект — есть незаполненные данные' : 'Геометрическая деталировка — на проверку технологу'}</h2>
    {report.issues.length ? <ul>{report.issues.map((item, i) => <li key={i}>{item.message}</li>)}</ul> : null}
    {report.notices.map(text=><p key={text}>{text}</p>)}
    <p>Паз, выборка утеплителя, угловые и Т-образные сопряжения, несущие перемычки и состав клеёного пакета — по утверждённым узлам. Размер заготовки панели указан по габариту; внутренние вырезы показаны на карте. Отходы внутри вырезов повторно не используются автоматически.</p>
    <p>Примечания: {report.settings.notes || 'Не заполнены. Укажите номер альбома узлов и требования к обработке.'}</p><p>Подготовил: __________________ Проверил: __________________ В производство: __________________</p>
    {scope === 'all' ? <section className="cut-print-surface"><h2>Каталог уникальных панелей</h2><PanelTable parts={report.parts} /></section> : null}
    {surfaces.map(surface => { const parts = report.parts.filter(part => part.surfaceId === surface.id); return <section className="cut-print-surface" key={surface.id}><h2>{surface.name} · {surface.frameOnly?'Каркас':'СИП '+surface.thickness+' мм'}</h2>{surface.blocked ? <p>Раскрой этой конструкции не сформирован: заполните данные проёмов.</p> : null}<Layout surface={surface} parts={parts} /><p>Начало координат — левый нижний угол развёртки стены; для перекрытия — координаты плана. Доборный ряд выделен светло-коричневым.</p><PanelTable parts={parts} /><h3>Контуры деталей и вырезов</h3>{groupPanels(parts).map(({part,qty}) => <p key={part.id}><b>{mark(part)} · ×{qty}</b>: {part.shape.map((ring, i) => `${i ? 'вырез' : 'контур'} [${ring.map(([x, y]) => `${n(x - part.x)};${n(y - part.y)}`).join(' / ')}]`).join(' · ')}</p>)}</section>; })}
    <section className="cut-print-surface"><h2>Шпонки и соединительные элементы</h2><MemberTable members={members} /></section>
    {scope==='all'?<section className="cut-print-surface"><h2>Крыша и путь нагрузки к фундаменту</h2><AssemblyDiagram assembly={report.assembly}/>{report.assembly.supports.map(s=><p key={s.id}>{s.mark}: {s.loadPath.text} · {s.nodeRef||'Узел не задан'}</p>)}<p>Панели: {report.cutting.panelCuts} резов, {n(report.cutting.panelCutLengthM)} м; пиломатериалы: {report.cutting.timberCuts} резов. Резы по картам заготовок и фигурным контурам, без пазов/выборки и угловых врубок.</p></section>:null}
    {scope==='all' ? <section className="cut-print-surface"><h2>Монтаж стартовой торцевой доски · вид сверху</h2><StarterBoardDiagram walls={report.starterBoards} /></section> : null}
    {surfaces.filter(s=>!s.blocked).map(surface=><section className="cut-print-surface" key={`members-${surface.id}`}><h2>{surface.name} · привязка соединителей</h2><p>Шаг {surface.effectiveStep} мм · направление {surface.layout?.direction || 'x'} · начало X {surface.layout?.originX ?? 'авто'}, Y {surface.layout?.originY ?? 'авто'}. Координаты концов и обработка — в ведомости.</p><Layout surface={surface} parts={report.parts.filter(p=>p.surfaceId===surface.id)} members={members.filter(m=>m.surfaceId===surface.id)} /></section>)}
    <Reconciliation report={report} />
    {scope === 'all' ? <><section className="cut-print-surface"><h2>Карты исходных панелей</h2><p>Прямоугольные заготовки; поворот {report.settings.allowRotation ? 'разрешён' : 'запрещён'}. Фигурные отходы повторно не используются. Отходы и пропил: {n(report.panelStock.wastePercent)}%. Количество заготовок не заменяет закупку в смете.</p><StockSheets report={report} /><h3>Прямоугольные остатки</h3>{report.panelStock.remnants.map((r,i)=><p key={i}>{r.sheet}: {n(r.width)}×{n(r.height)} мм, X {n(r.x)}, Y {n(r.y)}</p>)}</section><section className="cut-print-surface"><h2>Раскрой хлыстов {n(report.settings.stockLengthMm)} мм</h2>{report.timberStock.bars.map(bar => <p key={bar.id}><b>{bar.id} · {bar.material} {bar.profile}</b>: {bar.parts.map(part => `${mark(part)} — ${n(part.length)} мм (от ${n(part.start)})`).join('; ')}. Остаток {n(report.settings.stockLengthMm - bar.used)} мм.</p>)}</section></> : null}
    <p>Источник принципов соединений: «Как собрать СИП-дом самому?», Курмановы, печатные стр. 34–64 (перекрытия), 107–123 (проёмы), 12, 34, 60, 78, 143–144 (швы и кромки). Числовые настройки взяты из проекта; рекомендации книги не заменяют рабочие узлы.</p>
  </div>;
}

export default function CuttingScreen({ calculation }) {
  const [classic, setClassic] = useState(false);
  const { project, commit } = useProject();
  const [tab, setTab] = useState('panels'), [surfaceId, setSurfaceId] = useState(''), [selectedId, setSelectedId] = useState(''), [printScope, setPrintScope] = useState(null);
  const [memberKey, setMemberKey] = useState(''), [showMembers, setShowMembers] = useState(true);
  const [printError, setPrintError] = useState('');
  const settings = normalizeProductionCutting(project.settings.productionCutting);
  const inputKey = useMemo(()=>JSON.stringify({ project: { plan: project.plan, upperFloors: project.upperFloors, settings: project.settings, services: project.services, nodes: project.nodes, construction: project.construction }, calculation: { foundation: calculation.foundation, metrics: calculation.metrics, roof: calculation.roof, lines: calculation.lines } }),[project,calculation]);
  const [result, setResult] = useState({});
  useEffect(()=>{
    const worker = new Worker(new URL('../calculations/production-cutting.worker.js', import.meta.url), { type: 'module' });
    worker.onmessage = ({data})=>setResult({...data,inputKey});
    worker.onerror = ()=>setResult({error:'Ошибка фонового расчёта. Перезагрузите раздел.',inputKey});
    worker.postMessage(JSON.parse(inputKey));
    return ()=>worker.terminate();
  },[inputKey]);
  const pending = result.inputKey !== inputKey;
  const report = result.report;
  const surface = report?.surfaces.find(item => item.id === surfaceId) || report?.surfaces[0];
  const parts = report?.parts.filter(item => item.surfaceId === surface?.id) || [];
  const selected = parts.find(item => item.id === selectedId) || parts[0];
  const update = patch => commit(next => { next.settings.productionCutting = normalizeProductionCutting({ ...next.settings.productionCutting, ...patch }); return next; });
  const print = scope => { if (pending || !report) return; if (document.querySelector('.cutting-screen input[aria-invalid="true"]')) { setPrintError('Печать остановлена: исправьте несохранённые значения в исходных данных.'); return; } setPrintError(''); flushSync(() => setPrintScope(scope)); document.body.classList.add('print-production'); window.print(); };
  useEffect(() => { const cleanup = () => { document.body.classList.remove('print-production'); setPrintScope(null); }; window.addEventListener('afterprint', cleanup); return () => { window.removeEventListener('afterprint', cleanup); document.body.classList.remove('print-production'); }; }, []);
  if (!classic) return <DrawingWorkbench project={project} report={report} pending={pending} error={result.error} settings={settings} update={update} NumberInput={NumberInput} StarterBoardDiagram={StarterBoardDiagram} StockSheets={StockSheets} onSettings={()=>{setTab('settings');setClassic(true);}} onClassic={()=>setClassic(true)} />;
  return <section className="screen cutting-screen">
    <button className="secondary-button" onClick={()=>setClassic(false)}>Вернуться в окно чертежей</button>
    <div className="screen-header"><div><span className="eyebrow">ПРОИЗВОДСТВО ДОМОКОМПЛЕКТА</span><h1>Раскрой</h1><p>Панели, доборы по высоте, шпонки и соединительные элементы из текущего проекта.</p><p>{pending ? 'Пересчёт… Печать временно недоступна.' : report ? `${report.revision} · ${approvalLabels[report.approvalStatus]}` : ''}</p></div><button className="secondary-button" disabled={pending || !report || (!report.parts.length && !report.members.length)} onClick={() => print('all')}><Printer size={18} />Печать комплекта</button></div>
    <div className="cut-summary"><div><small>Детали панелей</small><strong>{report?.parts.length || 0}</strong><small>Уникальных: {report?.panelGroups.length || 0}</small></div><div><small>Доборы по высоте</small><strong>{report?.upperCourseCount || 0}</strong></div><div><small>Соединители</small><strong>{report?.members.length || 0}</strong></div><div><small>Панели-заготовки</small><strong>{report?.panelStock.sheets.length || 0}</strong></div></div>
    <button className="secondary-button" disabled={pending||!report} onClick={()=>print('album')}><Printer size={18}/>Печать монтажного альбома</button>
    {report?.cutting?<div className="cut-summary"><div><small>Целые панели</small><strong>{report.cutting.fullPanels}</strong></div><div><small>Резка панелей</small><strong>{report.cutting.panelCuts} резов</strong><small>{n(report.cutting.panelCutLengthM)} м</small></div><div><small>Фигурные резы / вырезы</small><strong>{report.cutting.shapedCuts}</strong></div><div><small>Резка пиломатериалов</small><strong>{report.cutting.timberCuts} резов</strong></div></div>:null}
    <p className="cut-note">Марки: Э — этаж, С — стена, ПГ — перегородка, П — панель, Ш — шпонка, Т — торцевая доска, ФР — фронтон, КР — кровля, СТ — стропило, СТП — стойка проёма (Л/П — стороны), К — каркас фронтона, М — мауэрлат, КН — коньковая доска, ОП — проектная опора. Резка показана по картам заготовок и фигурным контурам, без пазов, выборки и врубок.</p>
    <div className="cut-tabs" role="group" aria-label="Разделы раскроя">{[['panels', 'Панели и развёртки'], ['assembly', 'Крыша и опоры'], ['members', 'Шпонки и брус'], ['starter', 'Стартовая доска'], ['stock', 'Карты заготовок'], ['settings', 'Исходные данные']].map(([key, title]) => <button key={key} aria-pressed={tab === key} onClick={() => setTab(key)}>{title}</button>)}</div>
    {tab==='assembly' && report?<AssemblyPlan report={report} settings={settings} update={update} NumberInput={NumberInput}/>:null}
    {!pending && result.error ? <p className="cut-notice" role="alert">Не удалось построить раскрой: {result.error}. Проверьте размеры в исходных данных.</p> : null}
    {printError ? <p role="alert">{printError}</p> : null}
    {report?.notices.length ? <details className="cut-notice"><summary>Расхождения профилей со сметой: {report.notices.length}</summary>{report.notices.map(text=><p key={text}>{text}</p>)}</details> : null}
    {report?.issues.length ? <details className="cut-notice"><summary>Требуется заполнить / проверить: {report.issues.length}</summary><ul>{report.issues.map((item, i) => <li key={i}>{item.message}</li>)}</ul><button onClick={() => setTab('settings')}>Перейти к исходным данным</button></details> : <p className="cut-note">Геометрическая деталировка сформирована. Рабочие узлы и обработку проверяет технолог перед передачей в производство.</p>}
    {tab === 'settings' ? <div className="cut-card"><h2>Настройки производства</h2><p>Размер панели {n(report?.panelWidth)} × {n(report?.panelLength)} мм берётся из формул проекта. Деталировка каркаса перегородок связана со сметой и доставкой, если включён соответствующий режим. Остальные производственные переопределения требуют сверки со сметой; цены общего прайса не меняются.</p><div className="cut-fields">
      <label>Раскладка стен<select value={settings.wallPanelMode} onChange={e=>update({wallPanelMode:e.target.value})}><option value="full">Целые панели с подрезкой у проёмов</option><option value="grid">Разбиение по шагу каркаса</option></select></label>
      <DraftText label="Сечение каркаса фронтонов, мм" value={settings.gableFrameProfile} onChange={gableFrameProfile=>update({gableFrameProfile})}/>
      <DraftText label="Сечение укосин перегородок, мм" value={settings.partitionBraceProfile} onChange={partitionBraceProfile=>update({partitionBraceProfile})}/>
      <label className="cut-check"><input type="checkbox" checked={settings.partitionBracing} onChange={e=>update({partitionBracing:e.target.checked})}/>Укосины несущих перегородок · сечение 25×150 задано пользователем, соединения по проекту</label>
      <label className="cut-check"><input type="checkbox" checked={settings.bearingEdgeBoard} onChange={e=>update({bearingEdgeBoard:e.target.checked})}/>Доска на ребре под верхней обвязкой несущих перегородок</label>
      <label className="cut-check"><input type="checkbox" checked={settings.partitionCornerBacking} onChange={e=>update({partitionCornerBacking:e.target.checked})}/>Закладные стойки в углах и Т-примыканиях под обшивку</label>
      <DraftText label="Сечение контробрешётки по проекту, мм" value={settings.counterLathProfile} placeholder="Например 50×50, после проверки узла" onChange={counterLathProfile=>update({counterLathProfile})}/>
      <label><input type="checkbox" checked={settings.detailedFrameEstimate} onChange={e=>update({detailedFrameEstimate:e.target.checked})}/>Смета каркаса перегородок по деталировке (вместо укрупнённой нормы). Ручной расчёт по площади сохраняется.</label>
      <label className="cut-check"><input type="checkbox" checked={settings.ceilingBearingAlignment} onChange={e=>update({ceilingBearingAlignment:e.target.checked})}/>Привязывать сетку потолка к несущим стенам (приоритет над началом сетки)</label>
      <NumberInput label="Шаг силового каркаса" value={settings.frameStepMm} min={100} max={2500} onChange={value => update({ frameStepMm: value })} />
      <NumberInput label="Низ окон от пола по умолчанию" value={settings.windowSillMm} min={0} max={30000} onChange={value => update({ windowSillMm: value })} />
      <NumberInput label="Ширина пропила" value={settings.kerfMm} max={20} placeholder="Укажите пропил станка" onChange={value => update({ kerfMm: value })} />
      <NumberInput label="Припуск на каждый торец бруса" value={settings.endAllowanceMm} max={100} placeholder="0 — без припуска" onChange={value => update({ endAllowanceMm: value })} />
      <NumberInput label="Длина хлыста" value={settings.stockLengthMm} min={500} max={15000} onChange={value => update({ stockLengthMm: value })} />
      <NumberInput label="Ширина соединительной шпонки" value={settings.splineWidthMm} min={20} max={300} onChange={value => update({ splineWidthMm: value })} />
      <NumberInput label="Толщина торцевой доски" value={settings.edgeWidthMm} min={20} max={300} onChange={value => update({ edgeWidthMm: value })} />
    </div><label className="cut-check"><input type="checkbox" checked={settings.staggered} onChange={event => update({ staggered: event.target.checked })} />Шахматная раскладка пола и потолка</label>
    <CuttingControls settings={settings} report={pending ? null : report} update={update} NumberInput={NumberInput} />
    <details><summary>Изученные правила раскроя и сборки</summary>{PRODUCTION_GUIDANCE.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.text}</p><p>{item.source}{item.pages?` · стр. ${item.pages}`:''} · {item.status}. {item.url?<a href={item.url} target="_blank" rel="noreferrer">Источник</a>:null}</p><p>{item.limits}</p><p>{item.difference}</p></article>)}</details>
    <h2>Отметки окон и проёмов</h2><p>Ширина и высота берутся с плана. Низ окна по умолчанию — {n(settings.windowSillMm)} мм от пола, его можно изменить для каждого окна; дверь начинается от пола. Участок стены над дверью вычисляется из высоты стены и двери.</p><div className="cut-fields">{report?.openings.map(opening => <div key={opening.key}><NumberInput label={`${opening.name} · ${opening.width}×${opening.height}`} value={opening.sill} placeholder="Низ проёма от пола" onChange={value => update({ openingSills: { ...settings.openingSills, [opening.key]: value } })} />{opening.type === 'door' && opening.topClearance >= 0 ? <small>Над дверью: {n(opening.topClearance)} мм</small> : null}</div>)}</div>{!report?.openings.length ? <p className="cut-empty">Проёмов для SIP-раскроя пока нет. Добавьте окна и двери на плане.</p> : null}
    <h2>Добавочная высота стен</h2><p>При высоте больше длины панели автоматически формируется доборный ряд. Здесь можно задать производственный добор сверх высоты плана; он не увеличивает смету.</p><button onClick={() => update({ wallAdditions: {} })}>Сбросить добавочные высоты</button><div className="cut-fields">{report?.walls.map(wall => <NumberInput key={wall.key} label={`${wall.name} · база ${wall.baseHeight} мм`} value={settings.wallAdditions[wall.key] ?? 0} placeholder="Добавочная высота" max={10000} onChange={value => update({ wallAdditions: { ...settings.wallAdditions, [wall.key]: value } })} />)}</div>
    <h2>Специальные соединительные элементы</h2><p>Для ригелей, угловых закладных, Т-стыков, отдельных досок клеёного пакета и деталей пристроек.</p>{settings.manualParts.map((part, index) => <div className="cut-manual" key={part.id}><label>Название<input value={part.name || ''} placeholder="Например: закладная угла У-1" onChange={event => update({ manualParts: settings.manualParts.map((p, i) => i === index ? { ...p, name: event.target.value } : p) })} /></label><label>Сечение<input value={part.profile || ''} placeholder="145×90, по проекту" onChange={event => update({ manualParts: settings.manualParts.map((p, i) => i === index ? { ...p, profile: event.target.value } : p) })} /></label><NumberInput label="Чистая длина" value={part.length} onChange={value => update({ manualParts: settings.manualParts.map((p, i) => i === index ? { ...p, length: value } : p) })} /><NumberInput label="Количество" value={part.quantity} min={1} max={1000} suffix="шт." placeholder="Количество деталей" onChange={value => update({ manualParts: settings.manualParts.map((p, i) => i === index ? { ...p, quantity: value } : p) })} /><button aria-label={`Удалить деталь ${index + 1}`} onClick={() => update({ manualParts: settings.manualParts.filter((_, i) => i !== index) })}><Trash2 size={18} /></button></div>)}<button onClick={() => update({ manualParts: [...settings.manualParts, { id: crypto.randomUUID(), name: '', profile: '', length: '', quantity: 1 }] })}><Plus size={16} />Добавить деталь</button>
    <DraftText label="Указания производству" multiline value={settings.notes} placeholder="Номер альбома узлов, глубина выборки утеплителя, пазы, допуски, маркировка и требования к упаковке…" onChange={notes=>update({notes})} />
    <h2>Основание по книге</h2><p>«Как собрать СИП-дом самому?», А. С. Курманов, К. С. Курманов, Е. В. Курманова. Ниже — справочная карта крепежа с печатными страницами, не подтверждённый алгоритм производственного раскроя. Геометрическое разбиение не назначает несущие нормы; размеры пазов и соединений берутся из согласованного альбома рабочих узлов. Проверка соответствующих разворотов исходного скана для производственных правил ещё требуется.</p>{sources.map(source => <p key={source.id}><b>Стр. {source.pages} · {source.section}.</b> {source.summary}</p>)}</div> : null}
    {tab === 'panels' && report ? <div className="cut-card"><div className="cut-toolbar"><label>Конструкция<select aria-label="Конструкция" value={surface?.id || ''} onChange={event => { setSurfaceId(event.target.value); setSelectedId(''); }}>{report.surfaces.map(item => <option value={item.id} key={item.id}>{item.name}{item.blocked ? ' · нужны данные' : ''}</option>)}</select></label><button disabled={pending || !surface} onClick={() => print(surface.id)}><Printer size={16} />Печать конструкции</button></div>
      <SurfaceLayoutControls surface={surface} settings={settings} update={update} NumberInput={NumberInput} />
      <label className="cut-check"><input type="checkbox" checked={showMembers} onChange={e=>setShowMembers(e.target.checked)} />Показать марки соединителей</label>
      {surface?.blocked ? <p className="cut-empty">Развёртка заблокирована проверками исходных данных. Откройте список замечаний.</p> : <Layout surface={surface} parts={parts} selected={selected?.id} onSelect={setSelectedId} members={showMembers ? report.members.filter(m=>m.surfaceId===surface?.id) : []} onMemberSelect={key=>{setMemberKey(key);setTab('members');}} />}
      <p className="cut-note">Нажмите на деталь для размеров. Зелёный — выбранная деталь; светло-коричневый — добор по высоте. Оси X/Y — вдоль стены и от пола, для перекрытий — координаты плана.</p>
      {selected ? <div className="cut-detail"><div><h2>{mark(selected)} · ×{groupPanels(parts).find(group => group.instances.includes(selected.id))?.qty || 1}</h2><p>{n(selected.width)} × {n(selected.height)} × {selected.thickness} мм · {n(selected.area / 1e6)} м²</p><p>Контур и вырезы относительно левого нижнего угла детали (X; Y), мм:</p>{selected.shape.map((ring, i) => <p key={i}><b>{i ? `Вырез ${i}` : 'Контур'}:</b> {ring.map(([x, y]) => `${n(x - selected.x)}; ${n(y - selected.y)}`).join(' → ')}</p>)}</div><Layout surface={{ ...surface, geometry: [selected.shape] }} parts={[selected]} selected={mark(selected)} /></div> : null}<PanelTable parts={parts} onSelect={setSelectedId} />{surface?.frameOnly ? <><p>Каркасная конструкция: SIP-панели не предусмотрены. Детали каркаса показаны на развёртке и в ведомости ниже.</p><MemberTable members={report.members.filter(m=>m.surfaceId===surface.id)}/></> : !parts.length ? <p className="cut-empty">Детали пока не сформированы. Заполните контур и исходные данные.</p> : null}</div> : null}
    {tab === 'members' && report ? <div className="cut-card"><h2>Ведомость шпонок, бруса, стоек и обрамления</h2><p>Одинаковые детали объединены по материалу, сечению, длине и обработке; ×N не уменьшает количество для производства. Стойки проёмов идут по обеим сторонам, старые короткие вертикальные кромки помечены как заменённые и исключены из хлыстов. Нажмите марку для карточки. Состав и несущие узлы проверяет технолог.</p><MemberEditor member={report.members.find(m=>m.key===memberKey)} settings={settings} update={update} NumberInput={NumberInput} /><MemberTable members={report.members} onSelect={setMemberKey} />{!report.members.length ? <p className="cut-empty">Нет соединительных элементов. Сначала сформируйте панели или добавьте ручную деталь.</p> : null}</div> : null}
    {tab === 'starter' && report ? <div className="cut-card"><h2>План монтажа стартовой торцевой доски · вид сверху</h2><p>Зелёные участки — фактические нижние торцевые доски первого этажа из раскроя. Двери и проёмы от пола показаны разрывами; окно с подоконником выше пола не разрывает доску. Размеры указаны по оси каждой стены; схема не добавляет второй комплект доски в смету.</p><StarterBoardDiagram walls={report.starterBoards} /></div> : null}
    {tab === 'stock' && report ? <div className="cut-card"><h2>Карты исходных панелей</h2><p>Раскладка прямоугольных заготовок с пропилом. Заготовки разных толщин и семейств разделены. Фигурные отходы и вырезы не используются повторно автоматически; запас из сметы не считается изготовленной деталью.</p><StockSheets report={report} /><h2>Раскрой хлыстов</h2><div className="cut-bars">{report.timberStock.bars.map(bar => <article key={bar.id}><b>{bar.id} · {bar.material} {bar.profile}</b><div className="cut-bar">{bar.parts.map(part => <span key={part.id} style={{ left: `${part.start / settings.stockLengthMm * 100}%`, width: `${part.length / settings.stockLengthMm * 100}%` }} title={`${mark(part)}: ${part.length} мм`} />)}</div><small>{bar.parts.map(part => `${mark(part)}: ${n(part.length)} мм`).join(' · ')} · Остаток {n(settings.stockLengthMm - bar.used)} мм</small></article>)}</div></div> : null}
    {printScope && report ? createPortal(<PrintReport project={project} report={report} scope={printScope} />, document.body) : null}
    {tab === 'stock' && report ? <div className="cut-card"><p>Отходы и пропил относительно чистых деталей: {n(report.panelStock.wastePercent)}%. Поворот заготовок: {settings.allowRotation ? 'разрешён' : 'запрещён'}. Фигурные остатки автоматически не переиспользуются.</p><details><summary>Прямоугольные остатки: {report.panelStock.remnants.length}</summary>{report.panelStock.remnants.map((r,i)=><p key={i}>{r.sheet}: {n(r.width)}×{n(r.height)} мм, X {n(r.x)}, Y {n(r.y)}</p>)}</details><Reconciliation report={report} /></div> : null}
  </section>;
}
