import { productionMark as mark } from '../calculations/production-assembly.js';
import { MemberEditor, SurfaceLayoutControls } from './CuttingControls.jsx';
import { ConstructionSourceInfo } from './ProductionIdentityInfo.jsx';
import ConstructionSourcePicker from './ConstructionSourcePicker.jsx';
const fmt=value=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(value||0);
export default function DrawingInspector({surface,category,report,settings,update,NumberInput,project,chosenPanel,chosenMember,selection,links,onSettings}) {
  return <div className="workbench-properties">{surface?<div className="drawing-surface-properties" aria-label="Характеристики выбранной стены"><h2>{surface.name}</h2><dl><dt>Длина</dt><dd>{fmt(surface.width)} мм</dd><dt>Высота</dt><dd>{fmt(surface.height)} мм</dd><dt>Конструкция</dt><dd>{surface.frameOnly?'Каркас '+surface.frameProfile+' мм':'SIP '+surface.thickness+' мм'}</dd><dt>Назначение</dt><dd>{surface.bearing?'Несущая':surface.id.includes('-ПГ')?'Перегородка':'Наружная стена'}</dd><dt>Панели / элементы каркаса</dt><dd>{report.parts.filter(p=>p.surfaceId===surface.id).length} / {report.members.filter(m=>m.surfaceId===surface.id&&!m.excluded).length}</dd><dt>Проёмы</dt><dd>{surface.openings?.length||0}</dd></dl></div>:null}<details><summary>Привязка к источнику</summary><ConstructionSourceInfo surface={surface}/></details><ConstructionSourcePicker key={surface?.sourceBindingKey} surface={surface} plan={surface?.floor===1?project.plan:project.upperFloors?.[surface?.floor-2]} settings={settings} update={update}/><SurfaceLayoutControls surface={surface} settings={settings} update={update} NumberInput={NumberInput}/>{chosenPanel?<p><b>{mark(chosenPanel)} · ×{selection.length}</b> — {chosenPanel.width}×{chosenPanel.height}×{chosenPanel.thickness} мм; заготовка {chosenPanel.blankWidth??chosenPanel.width}×{chosenPanel.blankHeight??chosenPanel.height} мм. Геометрия из плана, раскладка из настроек конструкции.</p>:null}{chosenPanel?<details><summary>Контур и вырезы панели, мм</summary>{chosenPanel.shape.map((ring,i)=><p key={i}>{i?`Вырез ${i}`:'Контур'}: {ring.map(([x,y])=>`${fmt(x-chosenPanel.x)}; ${fmt(y-chosenPanel.y)}`).join(' → ')}</p>)}</details>:null}{chosenMember?<MemberEditor member={chosenMember} settings={settings} update={update} NumberInput={NumberInput}/>:null}
            {['walls','gables'].includes(category)?<details><summary>Связь стены с фронтоном</summary><p>Связь меняет совмещённый вид, а не количество деталей. Внутренний фронтон связывается только явно. Отметки и направление проверить по проекту.</p>{links.map(link=><div className="cut-fields" key={link.gable.id}><label>{link.gable.name} · {link.automatic?'из геометрии крыши':'проектная привязка'}<select value={link.wall?.layoutKey||''} onChange={e=>update({gableLinks:{...settings.gableLinks,[link.gable.layoutKey]:{wallKey:e.target.value,offset:0}}})}><option value="">Отдельная конструкция</option>{report.surfaces.filter(s=>s.planStart&&s.floor===link.gable.floor).map(s=><option key={s.layoutKey} value={s.layoutKey}>{s.name}</option>)}</select></label>{link.wall?<><NumberInput label={`${link.gable.id} · смещение вдоль стены`} value={link.offset} min={-100000} onChange={offset=>update({gableLinks:{...settings.gableLinks,[link.gable.layoutKey]:{...settings.gableLinks[link.gable.layoutKey],wallKey:link.wall.layoutKey,offset}}})}/><NumberInput label={`${link.gable.id} · высота основания`} value={link.elevation} onChange={elevation=>update({gableLinks:{...settings.gableLinks,[link.gable.layoutKey]:{...settings.gableLinks[link.gable.layoutKey],wallKey:link.wall.layoutKey,elevation}}})}/><label><input type="checkbox" checked={link.reverse} onChange={e=>update({gableLinks:{...settings.gableLinks,[link.gable.layoutKey]:{...settings.gableLinks[link.gable.layoutKey],wallKey:link.wall.layoutKey,reverse:e.target.checked}}})}/>Обратное направление</label></>:null}<button onClick={()=>{const next={...settings.gableLinks};delete next[link.gable.layoutKey];update({gableLinks:next});}}>Вернуть автоматическую связь</button></div>)}</details>:null}
            <button onClick={onSettings}>Все настройки производства, проёмов и ручных деталей</button></div>;
}
