import { partitionProcurement } from '../calculations/partition-procurement.js';
const f=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:3}).format(n);
export default function PartitionProcurement({report,project,settings,update,NumberInput}){
 const data=partitionProcurement(report,project.priceMat),rows=settings.partitionFasteners||[];
 const change=(id,patch)=>update({partitionFasteners:rows.map(r=>r.id===id?{...r,...patch}:r)});
 const exportCSV=()=>{const rows=[['Раздел','Материал','Количество','Ед.'],...data.boards.map(b=>['Перегородки',`Доска ${b.profile} × ${settings.stockLengthMm} мм`,b.count,'шт.']),...data.screws.map(r=>['Крепёж из сметы',r.name,r.qty,r.unit]),...data.manual.filter(r=>r.valid).map(r=>['Крепёж по проекту',r.name,r.qty,r.unit])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Перегородки-закупка.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section aria-label="Закупка перегородок"><h3>Все перегородки · доска и крепёж</h3><p>Отдельный заказ по раскрою перегородок всех этажей. Не прибавляйте его к общей закупке дома повторно. Без дополнительного запаса; припуски и пропил — из настроек раскроя.</p><button onClick={exportCSV}>Скачать закупку перегородок</button>
 <div className="cut-table-wrap"><table><thead><tr><th>Доска, мм</th><th>Заказать</th><th>Пог. м</th><th>м³</th></tr></thead><tbody>{data.boards.map(b=><tr key={b.profile}><td>{b.profile} × {settings.stockLengthMm}</td><td><strong>×{b.count} шт.</strong></td><td>{f(b.lengthM)}</td><td>{f(b.volumeM3)}</td></tr>)}</tbody></table></div>
 {data.unplaced.length?<p role="alert">Не вошли в закупочные доски: {data.unplaced.join(', ')}. Итог неполный — задайте допустимую длину или проект стыков.</p>:null}
 <h3>Крепёж перегородок</h3>{data.screws.length?<><p>Количество и единицы из действующей сметы SIP-перегородок, включая её нормы и запас.</p><div className="cut-table-wrap"><table><thead><tr><th>Позиция</th><th>Количество</th><th>Ед.</th></tr></thead><tbody>{data.screws.map(r=><tr key={`${r.catalogId}:${r.unit}`}><td>{[...new Set(r.names)].join('; ')}</td><td>{f(r.qty)}</td><td>{r.unit}</td></tr>)}</tbody></table></div></>:<p role="status">Автоматическая норма крепежа каркасных перегородок не задана. Это не нулевой расход: добавьте крепёж и количество по рабочим узлам.</p>}
 <p>Дополнительный крепёж по проекту — только для заказа в раскрое, не добавляется в смету автоматически. Не дублируйте позиции из таблицы выше.</p>
 {data.manual.map(r=><div className="cut-fields" key={r.id}><label>Крепёж<select aria-label="Крепёж перегородок" value={r.catalogId} onChange={e=>change(r.id,{catalogId:e.target.value,qty:''})}><option value="">Выберите позицию</option>{project.priceMat.filter(c=>/саморез|гвозд|крепёж|анкер|уголок/i.test(c.name)).map(c=><option key={c.id} value={c.id}>{c.name} · {c.unit}</option>)}</select></label><NumberInput label="Количество крепежа" value={r.qty} suffix={r.unit} onChange={qty=>change(r.id,{qty})}/><button onClick={()=>update({partitionFasteners:rows.filter(n=>n.id!==r.id)})}>Удалить позицию крепежа</button>{!r.valid?<p>Количество для заказа не задано.</p>:null}</div>)}
 <button disabled={rows.length>=100} onClick={()=>update({partitionFasteners:[...rows,{id:crypto.randomUUID(),catalogId:'',qty:''}]})}>Добавить крепёж перегородок</button></section>;
}
