import { Plus, Trash2 } from 'lucide-react';
import { SIP_GUIDE_ENTRIES } from '../data/sip-guide.js';
import { PRODUCTION_GUIDANCE } from '../data/production-guidance.js';
import { ProductionProfileControls, DraftText } from './CuttingControls.jsx';
const n=value=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:3}).format(Number(value)||0);
const sources=SIP_GUIDE_ENTRIES.filter(entry=>['sip-floor-ceiling-fasteners','sip-openings','sip-seam-screws','sip-roof'].includes(entry.id));
export default function ProductionSettings({project,report,pending,settings,update,NumberInput}) {
  return <div className="cut-card"><h2>Настройки производства</h2><p>Размер панели {n(report?.panelWidth)} × {n(report?.panelLength)} мм берётся из формул проекта. Деталировка каркаса перегородок связана со сметой и доставкой, если включён соответствующий режим. Остальные производственные переопределения требуют сверки со сметой; цены общего прайса не меняются.</p><div className="cut-fields">
      <label>Раскладка стен<select value={settings.wallPanelMode} onChange={e=>update({wallPanelMode:e.target.value})}><option value="full">Целые панели с подрезкой у проёмов</option><option value="grid">Разбиение по шагу каркаса</option></select></label>
      <DraftText label="Сечение каркаса фронтонов, мм" value={settings.gableFrameProfile} onChange={gableFrameProfile=>update({gableFrameProfile})}/>
      <DraftText label="Сечение укосин перегородок, мм" value={settings.partitionBraceProfile} onChange={partitionBraceProfile=>update({partitionBraceProfile})}/>
      <label>Направление укосины<select aria-label="Направление укосины" value={settings.partitionBraceDirection} onChange={e=>update({partitionBraceDirection:e.target.value})}><option value="auto">Автоматически · без пересечения проёмов</option><option value="left-right">Верхний левый угол → нижняя стойка справа</option><option value="right-left">Верхний правый угол → нижняя стойка слева</option></select></label>
      <NumberInput label="Глубина врезки укосины, мм · по проекту" value={settings.partitionBraceNotchDepthMm} onChange={partitionBraceNotchDepthMm=>update({partitionBraceNotchDepthMm})}/>
      <NumberInput label="Глубина врезки доски на ребре, мм · по проекту" value={settings.bearingEdgeNotchDepthMm} onChange={bearingEdgeNotchDepthMm=>update({bearingEdgeNotchDepthMm})}/>
      <label className="cut-check"><input type="checkbox" checked={settings.partitionBracing} onChange={e=>update({partitionBracing:e.target.checked})}/>Укосины несущих перегородок · сечение 25×150 задано пользователем, соединения по проекту</label>
      <label className="cut-check"><input type="checkbox" checked={settings.bearingEdgeBoard} onChange={e=>update({bearingEdgeBoard:e.target.checked})}/>Доска на ребре под верхней обвязкой несущих перегородок</label>
      <label className="cut-check"><input type="checkbox" checked={settings.partitionCornerBacking} onChange={e=>update({partitionCornerBacking:e.target.checked})}/>Закладные стойки в углах и Т-примыканиях под обшивку</label>
      <DraftText label="Сечение контробрешётки по проекту, мм" value={settings.counterLathProfile} placeholder="Например 50×50, после проверки узла" onChange={counterLathProfile=>update({counterLathProfile})}/>
      <label><input type="checkbox" checked={settings.detailedFrameEstimate} onChange={e=>update({detailedFrameEstimate:e.target.checked})}/>Смета каркаса перегородок по деталировке (вместо укрупнённой нормы). Ручной расчёт по площади сохраняется.</label>
      <label className="cut-check"><input type="checkbox" checked={settings.ceilingBearingAlignment} onChange={e=>update({ceilingBearingAlignment:e.target.checked})}/>Привязывать потолок и межэтажное перекрытие к фактическим несущим стенам</label>
      <NumberInput label="Допустимый пролёт соединителя по проекту, мм" value={settings.ceilingMaxSpanMm} onChange={v=>update({ceilingMaxSpanMm:v})}/>
      {report?.ceilingSupportChecks?.length?<details><summary>Опирание соединителей: {report.ceilingSupportChecks.filter(c=>c.status==='unsupported-end').length} с концами вне опор</summary><p>Проверка положения концов, не расчёт несущей способности. Пролёт и длина опирания требуют рабочего проекта. Проёмы не считаются опорами без подтверждённой перемычки.</p>{report.ceilingSupportChecks.map(c=><p key={c.memberId}>{c.memberId}: {n(c.lengthMm)} мм · начало {c.endSupports[0]?'на опоре':'вне опоры'}, конец {c.endSupports[1]?'на опоре':'вне опоры'} · {({'unsupported-end':'нужна опора или другая раскладка','needs-project-span':'пролёт не подтверждён','span-exceeded':'превышен заданный пролёт','geometry-checked':'геометрия совпала; узел проверить'})[c.status]}</p>)}</details>:null}
      <NumberInput label="Шаг силового каркаса" value={settings.frameStepMm} min={100} max={2500} onChange={value => update({ frameStepMm: value })} />
      <NumberInput label="Низ окон от пола по умолчанию" value={settings.windowSillMm} min={0} max={30000} onChange={value => update({ windowSillMm: value })} />
      <NumberInput label="Ширина пропила" value={settings.kerfMm} max={20} placeholder="Укажите пропил станка" onChange={value => update({ kerfMm: value })} />
      <NumberInput label="Припуск на каждый торец бруса" value={settings.endAllowanceMm} max={100} placeholder="0 — без припуска" onChange={value => update({ endAllowanceMm: value })} />
      <NumberInput label="Длина хлыста" value={settings.stockLengthMm} min={500} max={15000} onChange={value => update({ stockLengthMm: value })} />
      <NumberInput label="Ширина соединительной шпонки" value={settings.splineWidthMm} min={20} max={300} onChange={value => update({ splineWidthMm: value })} />
      <NumberInput label="Толщина торцевой доски" value={settings.edgeWidthMm} min={20} max={300} onChange={value => update({ edgeWidthMm: value })} />
    </div><label className="cut-check"><input type="checkbox" checked={settings.staggered} onChange={event => update({ staggered: event.target.checked })} />Шахматная раскладка пола и потолка</label>
    <ProductionProfileControls settings={settings} report={pending ? null : report} update={update} NumberInput={NumberInput} />
    <details><summary>Изученные правила раскроя и сборки</summary>{PRODUCTION_GUIDANCE.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.text}</p><p>{item.source}{item.pages?` · стр. ${item.pages}`:''} · {item.status}. {item.url?<a href={item.url} target="_blank" rel="noreferrer">Источник</a>:null}</p><p>{item.limits}</p><p>{item.difference}</p></article>)}</details>
    <h2>Отметки окон и проёмов</h2><p>Ширина и высота берутся с плана. Низ окна по умолчанию — {n(settings.windowSillMm)} мм от пола, его можно изменить для каждого окна; дверь начинается от пола. Участок стены над дверью вычисляется из высоты стены и двери.</p><div className="cut-fields">{report?.openings.map(opening => <div key={opening.key}><NumberInput label={`${opening.name} · ${opening.width}×${opening.height}`} value={opening.sill} placeholder="Низ проёма от пола" onChange={value => update({ openingSills: { ...settings.openingSills, [opening.key]: value } })} />{opening.type === 'door' && opening.topClearance >= 0 ? <small>Над дверью: {n(opening.topClearance)} мм</small> : null}</div>)}</div>{!report?.openings.length ? <p className="cut-empty">Проёмов для SIP-раскроя пока нет. Добавьте окна и двери на плане.</p> : null}
    <h2>Добавочная высота стен</h2><p>При высоте больше длины панели автоматически формируется доборный ряд. Здесь можно задать производственный добор сверх высоты плана; он не увеличивает смету.</p><button onClick={() => update({ wallAdditions: {} })}>Сбросить добавочные высоты</button><div className="cut-fields">{report?.walls.map(wall => <NumberInput key={wall.key} label={`${wall.name} · база ${wall.baseHeight} мм`} value={settings.wallAdditions[wall.key] ?? 0} placeholder="Добавочная высота" max={10000} onChange={value => update({ wallAdditions: { ...settings.wallAdditions, [wall.key]: value } })} />)}</div>
    <h2>Специальные соединительные элементы</h2><p>Для ригелей, угловых закладных, Т-стыков, отдельных досок клеёного пакета и деталей пристроек.</p>{settings.manualParts.map((part, index) => <div className="cut-manual" key={part.id}><label>Название<input value={part.name || ''} placeholder="Например: закладная угла У-1" onChange={event => update({ manualParts: settings.manualParts.map((p, i) => i === index ? { ...p, name: event.target.value } : p) })} /></label><label>Сечение<input value={part.profile || ''} placeholder="145×90, по проекту" onChange={event => update({ manualParts: settings.manualParts.map((p, i) => i === index ? { ...p, profile: event.target.value } : p) })} /></label><NumberInput label="Чистая длина" value={part.length} onChange={value => update({ manualParts: settings.manualParts.map((p, i) => i === index ? { ...p, length: value } : p) })} /><NumberInput label="Количество" value={part.quantity} min={1} max={1000} suffix="шт." placeholder="Количество деталей" onChange={value => update({ manualParts: settings.manualParts.map((p, i) => i === index ? { ...p, quantity: value } : p) })} /><button aria-label={`Удалить деталь ${index + 1}`} onClick={() => update({ manualParts: settings.manualParts.filter((_, i) => i !== index) })}><Trash2 size={18} /></button></div>)}<button onClick={() => update({ manualParts: [...settings.manualParts, { id: crypto.randomUUID(), name: '', profile: '', length: '', quantity: 1 }] })}><Plus size={16} />Добавить деталь</button>
    {settings.manualParts.length ? <details><summary>Смета ручных деталей раскроя</summary><p>По умолчанию ручные детали остаются только в раскрое. Для включения в смету выберите точно соответствующую позицию прайса и отметьте её. Чистый объём без запаса, крепежа и монтажа.</p>{settings.manualParts.map((part,index)=><div className="cut-manual" key={part.id}><strong>{part.name||`Деталь ${index+1}`} · {part.profile||'сечение не указано'} · {part.length||'—'} мм ×{part.quantity||'—'}</strong><label>Материал из прайса<select aria-label={`Материал сметы для детали ${index+1}`} value={part.estimateCatalogId||''} onChange={e=>update({manualParts:settings.manualParts.map((p,i)=>i===index?{...p,estimateCatalogId:e.target.value,estimateEnabled:false}:p)})}><option value="">Выберите материал</option>{project.priceMat.filter(row=>['м³','м3','м.п.','м'].includes(row.unit)).map(row=><option key={row.id} value={row.id}>{row.name} · {row.price} ₽/{row.unit}</option>)}</select></label><label className="cut-check"><input type="checkbox" disabled={!part.estimateCatalogId} checked={part.estimateEnabled===true} onChange={e=>update({manualParts:settings.manualParts.map((p,i)=>i===index?{...p,estimateEnabled:e.target.checked}:p)})}/>Включить в смету и доставку</label></div>)}</details> : null}
    <DraftText label="Указания производству" multiline value={settings.notes} placeholder="Номер альбома узлов, глубина выборки утеплителя, пазы, допуски, маркировка и требования к упаковке…" onChange={notes=>update({notes})} />
    <h2>Основание по книге</h2><p>«Как собрать СИП-дом самому?», А. С. Курманов, К. С. Курманов, Е. В. Курманова. Ниже — справочная карта крепежа с печатными страницами, не подтверждённый алгоритм производственного раскроя. Геометрическое разбиение не назначает несущие нормы; размеры пазов и соединений берутся из согласованного альбома рабочих узлов. Проверка соответствующих разворотов исходного скана для производственных правил ещё требуется.</p>{sources.map(source => <p key={source.id}><b>Стр. {source.pages} · {source.section}.</b> {source.summary}</p>)}</div>;
}
