import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react';
import { createPortal, flushSync } from 'react-dom';
import { useProject } from '../state/ProjectContext.jsx';
import { normalizeDocumentation } from '../state/project-documentation.js';
import { archiveRelease, createProjectRelease, openReleaseArchive, registerCsv, sealReleaseManifest, releaseZip } from '../calculations/project-release.js';
import { DOCUMENT_AUDIT, ENGINEERING_CHECKS } from '../data/project-documentation.js';
import ReleaseAlbum,{buildReleasePages,ReleaseTable} from './ReleaseAlbum.jsx';
import '../styles/project-documentation.css';
const ProductionHouse3D=lazy(()=>import('./ProductionHouse3D.jsx'));
const download=(name,text,type)=>{const url=URL.createObjectURL(new Blob([text],{type}));const link=document.createElement('a');link.href=url;link.download=name.replace(/[<>:"/\\|?*]/g,'-');link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function RecordEditor({record,onSave,label}) {
  const [draft,setDraft]=useState(record||{});
  useEffect(()=>setDraft(record||{}),[record]);
  return <fieldset className="release-record"><legend>{label}</legend><label>Документ-основание<input aria-label={`${label}: документ`} value={draft.evidence||''} onChange={e=>setDraft(d=>({...d,evidence:e.target.value}))}/></label><label>Проверяющий<input aria-label={`${label}: проверяющий`} value={draft.reviewer||''} onChange={e=>setDraft(d=>({...d,reviewer:e.target.value}))}/></label><label>Примечание<input value={draft.note||''} onChange={e=>setDraft(d=>({...d,note:e.target.value}))}/></label><button type="button" onClick={()=>onSave(draft)}>Зафиксировать для текущей ревизии</button><p>Запись со слов пользователя, не электронная подпись. Документ требуется проверить отдельно.</p></fieldset>;
}
export default function ProjectDocumentation({report,pending,onBack}) {
  const {project,commit,undo,redo,canUndo,canRedo}=useProject();
  const doc=normalizeDocumentation(project.documentation);
  const [release,setRelease]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[paper,setPaper]=useState('A3'),[printing,setPrinting]=useState(false),[selected,setSelected]=useState(''),[archiveIndex,setArchiveIndex]=useState('');
  const title=useRef(null),request=useRef(0);
  const [presentation,setPresentation]=useState('compact');
  const pages=useMemo(()=>release?buildReleasePages(release):[],[release]);
  const update=patch=>commit(next=>{next.documentation=normalizeDocumentation({...next.documentation,...patch});return next;});
  const saveRecord=(list,key,record)=>update({[list]:[...doc[list].filter(r=>r.key!==key),{...record,key,revision:report.revision}]});
  useEffect(()=>{const cleanup=()=>{document.body.classList.remove('print-production');if(title.current!==null){document.title=title.current;title.current=null;}setPrinting(false);};window.addEventListener('afterprint',cleanup);return()=>{request.current++;window.removeEventListener('afterprint',cleanup);cleanup();};},[]);
  const make=async mode=>{const token=++request.current;setBusy(true);setError('');try{await new Promise(resolve=>setTimeout(resolve,0));const draft=await createProjectRelease(project,{mode,presentation});const r=await sealReleaseManifest(draft,buildReleasePages(draft).map(({content,...meta})=>meta));if(token!==request.current)return;setRelease(r);setSelected('');setArchiveIndex('');}catch(e){if(token===request.current)setError(e.message);}finally{if(token===request.current)setBusy(false);}};
  const open=async index=>{const token=++request.current;setArchiveIndex(index);setBusy(true);setError('');setRelease(null);try{const r=await openReleaseArchive(doc.releases[Number(index)]);if(token===request.current){setRelease(r);setSelected('');}}catch(e){if(token===request.current)setError(e.message);}finally{if(token===request.current)setBusy(false);}};
  const keep=()=>{if(!release)return;const archive=archiveRelease(release);if(doc.releases.some(r=>r.digest===archive.digest))return;update({releases:[...doc.releases,archive]});setArchiveIndex(String(doc.releases.length));};
  const print=()=>{if(!release||busy)return;title.current=document.title;document.title=`${release.projectNumber}-${release.project.meta.projectName||'Домокомплект'}-выпуск-${release.number}`;flushSync(()=>setPrinting(true));document.body.classList.add('print-production');window.print();};
  const filename=`${release?.projectNumber||'Проект'}-выпуск-${release?.number||''}`;
  return <section className="screen project-documentation"><header><h1>Комплект проекта домокомплекта</h1><button onClick={onBack}>Вернуться к чертежам</button></header><p>АР, конструктив, производство, комплектация и монтаж — по одному снимку. Пока модель АР и каталожные соответствия неполны, возможен только черновой выпуск.</p><div className="release-controls"><label>Номер проекта<input aria-label="Номер комплекта" value={doc.projectNumber} placeholder={project.meta.projectNum} onChange={e=>update({projectNumber:e.target.value})}/></label><label>Примечание<input aria-label="Примечание комплекта" value={doc.note} onChange={e=>update({note:e.target.value})}/></label><button disabled={!canUndo} onClick={undo}>Отменить</button><button disabled={!canRedo} onClick={redo}>Повторить</button><button disabled={busy||pending||!report} onClick={()=>make('draft')}>Сформировать черновик</button><button disabled={busy||pending||!release?.validation.canRelease} title="Требуются закрытые ошибки, полная АР-модель и подтверждения" onClick={()=>make('released')}>В производство / монтаж</button><label>Сохранённые выпуски<select aria-label="Сохранённые выпуски" value={archiveIndex} onChange={e=>{if(e.target.value!=='')open(e.target.value);}}><option value="">Текущий черновик</option>{doc.releases.map((r,i)=><option key={r.digest} value={i}>№{r.number} · {r.date.slice(0,10)} · {r.revision}</option>)}</select></label></div>
  <label className="release-presentation">Содержание нового выпуска<select aria-label="Содержание выпуска" value={presentation} onChange={e=>setPresentation(e.target.value)}><option value="compact">Компактный альбом схем и 3D видов</option><option value="full">Подробное приложение со всеми ведомостями</option></select></label>
  {release&&!busy?<details className="release-live-model"><summary>Интерактивная 3D-модель снимка проекта</summary><Suspense fallback={<p>Загрузка 3D…</p>}><ProductionHouse3D report={release.report} project={release.project} large/></Suspense></details>:null}
  {busy?<p role="status">Формирую или проверяю снимок…</p>:null}{error?<p role="alert">{error}</p>:null}
  <details><summary>Матрица аудита документации</summary><div className="release-scroll"><ReleaseTable columns={['Документ','Источник данных','Реализовано','Не хватает','Проверка']} rows={DOCUMENT_AUDIT}/></div></details>
  <details><summary>Проверки конструктора и рабочие узлы</summary><p>Текущая ревизия раскроя: {report?.revision}. После изменения расчётных исходных данных подтверждения нужно внести повторно.</p>{report?ENGINEERING_CHECKS.map(([key,name])=><RecordEditor key={key} label={name} record={doc.confirmations.find(r=>r.key===key)} onSave={r=>saveRecord('confirmations',key,r)}/>):null}</details>
  <details><summary>Обоснования расхождений сметы и раскроя</summary><p>Можно документировать запас/избыток. Недостача, несопоставленный материал, неполная раскладка или неразмещённые детали не закрываются примечанием.</p>{report?.reconciliation.filter(r=>r.status==='compared'&&r.difference < -1e-6).map(row=><RecordEditor key={row.key} label={`${row.name}: ${row.difference} ${row.unit}`} record={doc.resolutions.find(r=>r.key===row.key)} onSave={r=>saveRecord('resolutions',row.key,r)}/>)}</details>
  {release&&!busy?<><h2>Выпуск {release.number} · {release.status==='draft'?'Черновик':'В производство / монтаж'}</h2><p>Проект {release.projectNumber} · {release.report.revision} · {release.date}. SHA-256: <code>{release.digest}</code></p><p>Архив хранится сжатым в .eft.json и автосохранении. Изменения живого проекта не переписывают выпуск; цены относятся к дате снимка, а не к текущему прайсу.</p><div className="release-controls"><button onClick={keep} disabled={doc.releases.some(r=>r.digest===release.digest)}>Сохранить выпуск в проект</button><button onClick={()=>download(`${filename}.release.json`,JSON.stringify(release,null,2),'application/json')}>Скачать снимок JSON</button><button onClick={()=>download(`${filename}-панели.csv`,registerCsv(release,'panels'),'text/csv;charset=utf-8')}>Ведомость панелей CSV</button><button onClick={()=>download(filename+".zip",releaseZip(release),"application/zip")}>Скачать машинный комплект ZIP</button><button onClick={()=>download(`${filename}-дерево.csv`,registerCsv(release,'timber'),'text/csv;charset=utf-8')}>Ведомость дерева CSV</button><label>Формат<select aria-label="Формат комплекта" value={paper} onChange={e=>setPaper(e.target.value)}><option>A3</option><option>A4</option></select></label><button onClick={print}>Печать / PDF</button></div><details open><summary>Причины блокировки: {release.validation.blocks.length}</summary><div className="release-scroll"><ReleaseTable columns={['Код','Причина','Путь исправления']} rows={release.validation.blocks.map(b=>[b.code,b.message,b.path])}/></div></details><details><summary>Все расхождения производства и сметы</summary><div className="release-scroll"><ReleaseTable columns={['Материал','Ед.','Производство','Смета','Разница','Статус']} rows={release.report.reconciliation.map(r=>[r.name,r.unit,r.required,r.purchased,r.difference,r.status])}/></div></details><h2>Перечень реально сформированных листов: {pages.length}</h2><label>Просмотр листа<select aria-label="Лист комплекта" value={selected||pages[0]?.id||''} onChange={e=>setSelected(e.target.value)}>{pages.map(p=><option key={p.id} value={p.id}>{p.id} · {p.title}</option>)}</select></label><ReleaseAlbum release={release} pages={pages} selectedIds={[selected||pages[0]?.id]} paper={paper} preview/></>:null}
  {printing&&release?createPortal(<ReleaseAlbum release={release} pages={pages} paper={paper}/>,document.body):null}
  </section>;
}
