import { buildMountingPages, TechnicalDrawing } from './MountingAlbum.jsx';
import { PrintPlanDiagram } from '../components/PrintProjectDiagrams.jsx';
import { calculateClearAreas } from '../calculations/plan-clear-area.js';
import { RELEASE_SOURCES } from '../data/project-documentation.js';
import { SIP_GUIDE_ENTRIES } from '../data/sip-guide.js';
import { groupStockMaps } from '../calculations/project-release.js';
import { compactReleasePages } from './CompactReleasePages.jsx';
const chunks=(rows,n=10)=>Array.from({length:Math.ceil(rows.length/n)},(_,i)=>rows.slice(i*n,i*n+n));
const fmt=value=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:3}).format(value??0);
export function ReleaseTable({columns,rows}) {return <table className="release-table"><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v??'—'}</td>)}</tr>)}</tbody></table>;}

export function buildReleasePages(release) {
  if(release.presentation?.mode==='compact')return compactReleasePages(release);
  const {project,report,registers}=release,pages=[],counts={};
  const add=(group,title,content,info={})=>{const id=`${group}${String(counts[group]=(counts[group]||0)+1).padStart(2,'0')}`;pages.push({id,group,title,content,scale:'не в масштабе',units:'мм; площади м²; объёмы м³',direction:'см. направление вида на схеме',axes:'Проектные оси не назначены',...info});return id;};
  add('ОБ','Титульный лист',<><h1>ЭФТ · Проект домокомплекта SIP</h1><h2>{project.meta.projectName||project.meta.buildingType}</h2><p>Проект {release.projectNumber} · выпуск {release.number} · {release.status==='released'?'В производство / монтаж':'ЧЕРНОВИК — НЕ ДЛЯ ИЗГОТОВЛЕНИЯ И МОНТАЖА'}</p><p>Заказчик: {project.meta.customer||'не указан'}<br/>Адрес: {project.meta.address||'не указан'}<br/>Автор: {project.meta.author||'не указан'}</p><p>Дата снимка: {release.date}. Ревизия: {report.revision}.</p><p>Проверка статуса в программе не является электронной подписью, инженерным расчётом или согласованием.</p><p>SHA-256: {release.digest}</p><p>{project.documentation.note}</p></>,{direction:'не применяется',axes:'не применяется'});
  add('ОБ','Исходные параметры и ограничения',<><p>Все документы используют один сохранённый снимок. Изменения текущего проекта не меняют этот выпуск. Параметры и цены взяты из проекта; расчётные формулы не заменялись.</p><ReleaseTable columns={['Параметр','Значение']} rows={[
    ['Габарит первого этажа, м',`${project.plan.house.w} × ${project.plan.house.h}`],['Этажей',report.assembly.floors.length],['Высота наружных стен первого этажа, м',project.plan.wallHeight],['Параметры SIP',JSON.stringify(project.settings.sip)],['Заготовка панели, мм',`${report.panelLength} × ${report.panelWidth}`],['Заготовка пиломатериала, мм',report.settings.stockLengthMm],['Сетка каркаса, мм',report.settings.frameStepMm],['Пропил / припуск торца, мм',`${report.settings.kerfMm} / ${report.settings.endAllowanceMm}`],['Статус исходного раскроя',report.approvalStatus],['Смета, ₽',fmt(release.calculation.totals.total)],
  ]}/><p>Основание, сечения, пролёты, снег/ветер, крепёж и рабочие узлы требуют подтверждения конструктора. Фасады и общие разрезы АР в текущей автоматической модели неполны.</p></>);
  // Contents inserted after all pages exist; no old album page numbers leak in.
  const contentIndex=pages.length;
  for(const [i,floor]of report.assembly.floors.entries()){
    const plan=i===0?project.plan:project.upperFloors[i-1];
    add('АР',`План этажа ${floor.floor}`,<><PrintPlanDiagram plan={plan} pileSettings={project.settings.piles} roofSettings={project.settings.roof} floorOpening={i===0?project.upperFloors[0]?.floorOpenings:plan.floorOpenings} options={{showPiles:false,showBinding:false,showRoof:false,showRooms:true,showOpenings:true,showDimensions:true}}/><p>План по сохранённой геометрии, без самовольного назначения проектных осей и высот. Недостающие оси перечислены в реестре выпуска.</p></>,{direction:'сверху'});
    const clear=calculateClearAreas(plan);
    for(const [j,list]of chunks((plan.rooms||[]).filter(r=>r.include!==false).map(r=>[r.name||r.id,fmt(clear.rooms[r.id]?.contourArea),fmt(clear.rooms[r.id]?.clearArea)])).entries())add('АР',`Экспликация этажа ${floor.floor} · ${j+1}`,<ReleaseTable columns={['Помещение','Площадь по границам, м²','Площадь в свету, м²']} rows={list}/>,{direction:'сверху'});
  }
  for(const [i,list]of chunks(report.openings).entries())add('АР',`Ведомость проёмов · ${i+1}`,<ReleaseTable columns={['ID / стена','Тип','Ширина, мм','Высота, мм','Низ / верх, мм']} rows={list.map(o=>[o.key||o.id,o.type,o.width,o.height,`${o.sill} / ${Number(o.sill)+Number(o.height)}`])}/>);
  const existing=buildMountingPages({...report,members:report.members.filter(m=>!m.excluded)}).filter(p=>!/^Состав монтажного|Ведомость листов монтажного/.test(p.title));
  for(const p of existing)add('КД',p.title,p.content,{direction:/план|поле|покрытие|обвязки/i.test(p.title)?'сверху; разрезы отдельно':'со стороны показанной на локаторе / по подписи вида'});
  const sheetRefs=id=>pages.filter(p=>p.group==='КД'&&p.title.includes(report.surfaces.find(s=>s.id===id)?.name||'__none__')).map(p=>p.id).join(', ');
  for(const kind of ['panels','timber'])for(const [i,list]of chunks(registers[kind]).entries())add('ПР',`${kind==='panels'?'Панели':'Деревянные детали'} · ведомость ${i+1}`,<ReleaseTable columns={['Марка','Материал','Габарит / сечение и длина, мм','Кол.','Обработка / узел','Монтажные листы']} rows={list.map(r=>[r.mark,r.material,r.size,`×${r.qty}`,r.processing+(r.nodeRef?` · ${r.nodeRef}`:''),[...new Set(r.ids.map(id=>sheetRefs([...report.parts,...report.members].find(m=>m.id===id)?.surfaceId)))].filter(Boolean).join('; ')||'Сводные листы КД'])}/>);
  for(const {item:sheet,qty}of groupStockMaps(report.panelStock.sheets,'panel'))add('ПР',`Карта панели-заготовки ${sheet.id} · ×${qty}`,<><TechnicalDrawing surface={{id:sheet.id,name:sheet.id,horizontal:true,geometry:[[[[0,0],[sheet.width,0],[sheet.width,sheet.height],[0,sheet.height],[0,0]]]]}} parts={sheet.parts.map(p=>({...p,shape:[[[p.x,p.y],[p.x+p.width,p.y],[p.x+p.width,p.y+p.height],[p.x,p.y+p.height],[p.x,p.y]]],displayMark:report.parts.find(r=>r.id===p.id)?.displayMark}))}/><p>Заготовка {sheet.width}×{sheet.height} мм. Показаны размещаемые прямоугольники; фигурная обработка — по полигону детали в каталоге КД. Карта не является программой ЧПУ. Пропил {report.settings.kerfMm} мм.</p></>,{direction:'со стороны лицевой обшивки'});
  for(const [i,list]of chunks(groupStockMaps(report.timberStock.bars,'timber'),6).entries())add('ПР',`Карты пиломатериалов · ${i+1}`,<ReleaseTable columns={['Хлыст','Материал / сечение','Размещение: ID, начало / длина, мм','Свободный конец, мм']} rows={list.map(({item:b,qty})=>[`${b.id} · ×${qty}`,`${b.material} ${b.profile}`,b.parts.map(p=>`${p.displayMark||p.id}: ${p.start} / ${p.length}`).join('; '),fmt(report.settings.stockLengthMm-Math.max(0,...b.parts.map(p=>p.start+p.length)))])}/>);
  for(const [i,list]of chunks(report.panelStock.remnants).entries())add('ПР',`Остатки панелей · ${i+1}`,<ReleaseTable columns={['Заготовка','X / Y, мм','Размер, мм']} rows={list.map(r=>[r.sheet,`${r.x} / ${r.y}`,`${r.width} × ${r.height}`])}/>);
  for(const [i,list]of chunks(registers.packaging).entries())add('ПР',`Упаковочные группы · ${i+1}`,<ReleaseTable columns={['Группа','Назначение','Деталей','Марки']} rows={list.map(g=>[g.id,g.name,g.ids.length,[...new Set(g.ids.map(id=>[...report.parts,...report.members].find(m=>m.id===id)?.displayMark))].join(', ')])}/>);
  const labels=[...registers.panels,...registers.timber];
  for(const [i,list]of chunks(labels,6).entries())add('ПР',`Этикетки типоразмеров · ${i+1}`,<div className="release-labels">{list.map(r=><article key={r.mark}><h2>{r.mark} · ×{r.qty}</h2><p>{r.material} · {r.size} мм</p><p>{release.projectNumber} · {report.revision} · выпуск {release.number}</p><p>Упаковки: {registers.packaging.filter(g=>g.ids.some(id=>r.ids.includes(id))).map(g=>g.id).join(', ')}</p><p>Этикетка группы; полный список позиций в JSON / CSV.</p></article>)}</div>);
  for(const [i,list]of chunks(release.catalog).entries())add('КМ',`Комплектация и цены · ${i+1}`,<ReleaseTable columns={['catalogId','Номенклатура','Ед.','Кол.','Цена, ₽','Проверка']} rows={list.map(r=>[r.catalogId,r.name,r.unit,fmt(r.qty),fmt(r.price),r.issues.join('; ')||(r.conversion?`${r.conversion.factor} ${r.conversion.unit} · по сметной модели`:'Каталог найден')])}/>);
  for(const [i,list]of chunks(report.reconciliation).entries())add('КМ',`Сверка производства со сметой · ${i+1}`,<ReleaseTable columns={['Материал','Ед.','Требуется','Закуплено','Разница','Статус']} rows={list.map(r=>[r.name,r.unit,fmt(r.required),r.purchased==null?'не сопоставлено':fmt(r.purchased),r.difference==null?'не сопоставлено':fmt(r.difference),r.status])}/>);
  const stages=[
    ['Приёмка и хранение','Сверить марки и количество с ведомостями и этикетками. Проверить повреждения, сухое основание, укрытие от осадков и проветривание.','ПР'],
    ['Основание и обвязка','Проверить габариты, диагонали, отметки опор, стыки на опорах и гидроизоляцию по рабочему узлу.','КД'],
    ['Пол и перекрытия','Разложить по маркам; проверить опирание соединителей и лестничные вырезы. Герметизация и крепёж — по подтверждённому узлу.','КД'],
    ['Стены и перегородки','Сверить проёмы/отметки, углы, стойки примыканий, вертикальность и временную устойчивость. Не менять несущие элементы по месту без согласования.','КД'],
    ['Фронтоны и кровля','Проверить опоры, свесы, стыки, путь нагрузки и раскладку покрытия. Подъём — только по утверждённому плану такелажа.','КД'],
    ['Защита и приёмка','Повторно проверить герметизацию швов/проходок после инженерных работ, защиту от воды, соответствие марок и рабочим узлам. Допуски брать из проекта, не из этого чек-листа.','КМ'],
  ];
  for(const [name,note,group]of stages)add('МН',name,<><h2>{name}</h2><p>{note}</p><p>Листы: {pages.filter(p=>p.group===group).map(p=>p.id).join(', ')}.</p><p>Марки: см. ведомости ПР и соответствующий монтажный лист КД. Каждая физическая позиция связана через технический ID в машинной ведомости.</p><p>Приёмка: результат, фактические отклонения, ответственный и дата фиксируются в акте по рабочему проекту. Это справочная последовательность, не назначение крепежа или допусков.</p><p>Основание рекомендаций: SIPA BEST 5, PDF 2–3; SIPA BEST 7, PDF 1–3; БАФ, листы 4–5 / PDF 3–4 и лист 8 / PDF 7. Применимость к конкретному комплекту проверяет проектировщик.</p></>);
  for(const [i,list]of chunks(release.validation.blocks,8).entries())add('ВП',`Открытые вопросы и блокировки · ${i+1}`,<ReleaseTable columns={['Код','Причина','Путь исправления']} rows={list.map(b=>[b.code,b.message,b.path])}/>);
  for(const [i,list]of chunks(project.documentation.confirmations).entries())add('ВП',`Проверки конструктора · ${i+1}`,<ReleaseTable columns={['Проверка','Ревизия','Документ-основание','Проверяющий']} rows={list.map(r=>[r.key,r.revision,r.evidence,r.reviewer])}/>);
  add('ВП','Изменения между выпусками',<ReleaseTable columns={['Раздел','До','После']} rows={release.changes.map(r=>[r.section,r.before,r.after])}/>);
  add('ВП','Источники и область применения',<>{RELEASE_SOURCES.map(s=><p key={s.url}><a href={s.url}>{s.name}</a> · {s.pages}. {s.scope}. {s.limits}</p>)}{SIP_GUIDE_ENTRIES.filter(s=>['sip-floor-ceiling-fasteners','sip-openings','sip-roof'].includes(s.id)).map(s=><p key={s.id}>{s.title}: Курмановы, печатные страницы {s.pages}. {s.scope}. {s.limits} Справочная ссылка, не новое правило расчёта.</p>)}</>);
  let contentCount=Math.ceil(pages.length/16);
  while(Math.ceil((pages.length+contentCount)/16)>contentCount)contentCount++;
  const contents=Array.from({length:contentCount},(_,i)=>({id:`ОБВ${i+1}`,group:'ОБ',title:`Перечень листов · ${i+1}`,scale:'не в масштабе',units:'мм',direction:'не применяется',axes:'не применяется'}));
  pages.splice(contentIndex,0,...contents);
  chunks(pages.map(p=>[p.id,p.group,p.title]),16).forEach((list,i)=>{contents[i].content=<ReleaseTable columns={['Лист','Раздел','Наименование']} rows={list}/>;});
  return pages;
}
export default function ReleaseAlbum({release,pages=buildReleasePages(release),selectedIds,paper='A3',preview=false}) {
  return <div className={`${preview?'drawing-preview':'production-print'} mounting-album release-album paper-${paper}`}>{pages.filter(p=>!selectedIds||selectedIds.includes(p.id)).map(p=><section key={p.id} className="mounting-sheet" data-sheet-id={p.id}><header>{p.id} · {p.title}</header><div className="release-sheet-meta">Проект {release.projectNumber} · {release.report.revision} · выпуск {release.number} · {release.date.slice(0,10)} · {release.status==='released'?'В производство / монтаж':'ЧЕРНОВИК'}<br/>Масштаб: {p.scale}. Единицы: {p.units}. Вид: {p.direction}. Оси: {p.axes}.</div><div className="mounting-content">{p.content}</div><footer>{p.title} · {p.id} · снимок SHA256 {release.digest.slice(0,16)}</footer></section>)}</div>;
}
