import {useState} from 'react';
import {calculateDeliveryVolume} from '../calculations/delivery-volume.js';
const fmt=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:3}).format(n);
function VolumeInput({value,onChange,label}){const [draft,setDraft]=useState(value),[error,setError]=useState('');return <label>{label}<input aria-label={label} type="number" min="0" step="0.001" value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{if(draft!==''&&(!Number.isFinite(Number(draft))||Number(draft)<0)){setError('Введите неотрицательный объём');return;}setError('');onChange(draft===''?'':Number(draft));}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/>{error?<small role="alert">{error}</small>:null}</label>;}
export default function DeliveryVolume({project,calculation,onChange}){
 const result=calculateDeliveryVolume(project,calculation),settings=project.settings.delivery.volumeGroups||{};
 const patch=(key,value)=>onChange({...settings,[key]:{...settings[key],...value}});
 return <section aria-label="Объёмы материалов для доставки"><h2>Объёмы материалов для доставки</h2><p>По закупочным строкам сметы, без работ и доставки. Панели и пиломатериалы вынесены из остальных разделов — повторного учёта нет. Автоматический объём геометрический, без поддонов и промежутков при укладке; транспортную упаковку учтите ручным объёмом категории.</p>
 <h3>{result.complete?'Общий объём':'Известный объём (итог неполный)'}: {fmt(result.total)} м³</h3><p>Сводка не меняет стоимость доставки и прежний расчёт разгрузки. Стоимость настраивается отдельно ниже.</p>
 {result.categories.map(g=><article key={g.key} className="panel"><h3>{g.title} · {g.effectiveVolume===null?'Объём не задан':`${fmt(g.effectiveVolume)} м³`}</h3><div className="form-grid"><label>Способ расчёта<select aria-label={`Расчёт объёма: ${g.title}`} value={g.mode} onChange={e=>patch(g.key,{mode:e.target.value})}><option value="auto">Автоматически</option><option value="manual">Вручную — объём всей категории</option></select></label>{g.mode==='manual'?<VolumeInput key={`${g.key}:${g.volume}`} label={`Объём: ${g.title}, м³`} value={g.volume} onChange={volume=>patch(g.key,{volume})}/>:null}</div>{!g.complete?<p role="status">{g.mode==='auto'?`Объём не задан для ${g.unknown} позиций. Укажите общий объём категории вручную.`:'Введите объём всей категории, включая упаковку.'}</p>:null}<details><summary>Материалы · {g.rows.length} поз. · автоматически {fmt(g.autoVolume)} м³</summary>{g.rows.map(r=><p key={r.id}><b>{r.name}</b> · {fmt(r.qty)} {r.unit} → {r.volume===null?'Объём не задан':`${fmt(r.volume)} м³`}<br/><small>{r.formula}</small></p>)}</details></article>)}
 {!result.categories.length?<p>В смете нет включённых материалов.</p>:null}</section>;
}
