import { useEffect, useMemo, useState } from 'react';
import { Brush, Building2, CheckCircle2, Droplets, Layers3 } from 'lucide-react';
import { DEFAULT_INTERNAL, inferInternalPreset, internalRoomKey } from '../calculations/internal-model.js';
import { NumberField, SelectField, Stat, Toggle } from './ui.jsx';
import { formatNumber } from '../utils/format.js';

const FLOOR=[{value:'none',label:'Без чистового пола'},{value:'laminate',label:'Ламинат'},{value:'tile',label:'Плитка / керамогранит'}];
const SUBSTRATE=[{value:'none',label:'Без дополнительного основания'},{value:'osb12',label:'OSB-3 12 мм'},{value:'gvl12',label:'ГВЛВ 12,5 мм · 1 слой (проектное решение)'},{value:'gvl20',label:'Элемент пола ГВЛВ 20 мм'},{value:'gvl-double',label:'ГВЛВ 12,5 мм · 2 слоя'}];
const WALL=[{value:'none',label:'Без чистовой отделки'},{value:'timber',label:'Имитация бруса'},{value:'drywall',label:'Гипсокартон / ГВЛ'}];
const FRAME=[{value:'direct',label:'Непосредственно на SIP'},{value:'wood25',label:'Брусок 25×50 мм'},{value:'wood50',label:'Брусок 50×50 мм'},{value:'metal',label:'Металлический каркас ПП 60×27'}];
const BOARD=[{value:'standard',label:'ГКЛ 12,5 мм'},{value:'moisture',label:'ГКЛВ 12,5 мм'},{value:'fire',label:'ГКЛО 12,5 мм'},{value:'gvl',label:'ГВЛВ 12,5 мм'}];
const FINAL=[{value:'none',label:'Только заделка швов Q2'},{value:'paint',label:'Подготовка Q3/Q4 + покраска'},{value:'wallpaper',label:'Подготовка + обои'},{value:'tile',label:'Плитка по стенам'}];
const CEILING=[{value:'none',label:'Без потолка / второй свет'},{value:'timber',label:'Имитация бруса'},{value:'stretch',label:'Натяжной потолок'}];
const CEILING_FRAME=FRAME.filter(item=>item.value!=='metal');
const STRETCH=[{value:'pvc',label:'ПВХ-полотно'},{value:'fabric',label:'Тканевое полотно'}];

export function InternalEditor({project,calculation,commit}) {
  const detailed=project.settings.internal?.assemblyVersion===1&&project.settings.internal?.mode!=='legacy';
  const rooms=calculation.internal?.rooms||[];
  const [selectedKey,setSelectedKey]=useState('');
  useEffect(()=>{if(!rooms.length)return;if(!rooms.some(room=>internalRoomKey(room.floor,room.id)===selectedKey))setSelectedKey(internalRoomKey(rooms[0].floor,rooms[0].id));},[rooms,selectedKey]);
  const room=useMemo(()=>rooms.find(item=>internalRoomKey(item.floor,item.id)===selectedKey)||rooms[0],[rooms,selectedKey]);
  const stored=room?project.settings.internal.roomFinishes?.[internalRoomKey(room.floor,room.id)]:null;
  const values=room?{...inferInternalPreset(room.name),...(stored||{})}:null;
  const updateGlobal=(key,value)=>commit(next=>{next.settings.internal={...DEFAULT_INTERNAL,...next.settings.internal,[key]:value};return next;});
  const updateRoom=(changes)=>{if(!room)return;commit(next=>{const settings={...DEFAULT_INTERNAL,...next.settings.internal};const key=internalRoomKey(room.floor,room.id);settings.roomFinishes={...(settings.roomFinishes||{}),[key]:{...inferInternalPreset(room.name),...(settings.roomFinishes?.[key]||{}),...changes}};next.settings.internal=settings;return next;});};
  const resetRoom=()=>{if(!room)return;commit(next=>{const key=internalRoomKey(room.floor,room.id);const finishes={...(next.settings.internal.roomFinishes||{})};delete finishes[key];next.settings.internal.roomFinishes=finishes;return next;});};
  if(!detailed)return <div className="internal-upgrade"><Layers3/><div><strong>Сохранён прежний расчёт внутренней отделки</strong><p>Он оставлен без изменений, чтобы старая смета не подорожала автоматически. Перейдите на расчёт по помещениям — будут учтены основания пола, каркасы, гидроизоляция, плинтусы и потолочные узлы.</p></div><button className="button primary" onClick={()=>commit(next=>{next.settings.internal={...DEFAULT_INTERNAL,...next.settings.internal,assemblyVersion:1,mode:'rooms',roomFinishes:{}};return next;})}>Перейти на подробный расчёт</button></div>;
  return <div className="internal-editor">
    <section className="internal-overview">
      <Stat label="Полы" value={`${formatNumber(calculation.internal?.totals.floorArea||0)} м²`}/><Stat label="Стены" value={`${formatNumber(calculation.internal?.totals.wallArea||0)} м²`}/><Stat label="Потолки" value={`${formatNumber(calculation.internal?.totals.ceilingArea||0)} м²`}/><Stat label="Помещения" value={`${rooms.length} шт`}/>
    </section>
    <details className="internal-global"><summary>Общие нормы и округление</summary><div className="form-grid four"><NumberField label="Запас материалов" value={(project.settings.internal.reserve||1.1)*100-100} suffix="%" step={1} onChange={value=>updateGlobal('reserve',1+value/100)}/><NumberField label="Шаг обрешётки" value={project.settings.internal.battenStep} suffix="м" step={.05} min={.2} onChange={value=>updateGlobal('battenStep',value)}/><NumberField label="Расход краски на слой" value={project.settings.internal.paintConsumption} suffix="л/м²" step={.01} onChange={value=>updateGlobal('paintConsumption',value)}/><NumberField label="Плиточный клей" value={project.settings.internal.tileGlueConsumption} suffix="кг/м²" step={.1} onChange={value=>updateGlobal('tileGlueConsumption',value)}/><NumberField label="Минимум натяжного потолка" value={project.settings.internal.stretchMinimumArea} suffix="м²/комната" step={1} onChange={value=>updateGlobal('stretchMinimumArea',value)}/><NumberField label="Глубина откосов" value={project.settings.internal.slopeDepth} suffix="м" step={.01} onChange={value=>updateGlobal('slopeDepth',value)}/>{project.settings.links.internalFinishFromPlan===false?<NumberField label="Межкомнатные двери вручную" value={project.settings.internal.doors} suffix="шт" step={1} onChange={value=>updateGlobal('doors',value)}/>:null}</div><div className="internal-toggle-grid"><Toggle label="Подготовка основания пола" checked={project.settings.internal.includePreparation!==false} onChange={value=>updateGlobal('includePreparation',value)}/><Toggle label="Пороги межкомнатных дверей" checked={project.settings.internal.includeThresholds!==false} onChange={value=>updateGlobal('includeThresholds',value)}/><Toggle label="Откосы окон и входных дверей" checked={project.settings.internal.includeSlopes!==false} onChange={value=>updateGlobal('includeSlopes',value)}/></div><p>Листовые материалы округляются вверх. Брусок округляется до закупки шестиметровыми хлыстами. Нормы остаются редактируемыми для конкретного проекта.</p></details>
    <div className="internal-workspace">
      <nav className="internal-room-list" aria-label="Помещения внутренней отделки">{rooms.map(item=>{const key=internalRoomKey(item.floor,item.id);const itemSettings=item.settings;return <button key={key} className={key===selectedKey?'active':''} onClick={()=>setSelectedKey(key)}><span><Building2/> {item.floor} этаж</span><strong>{item.name}</strong><small>{formatNumber(item.area)} м² · {itemSettings.floorFinish==='tile'?'плитка':itemSettings.floorFinish==='laminate'?'ламинат':'без пола'}</small></button>;})}</nav>
      {room&&values?<section className="internal-room-card">
        <header><div><span>{room.floor} этаж</span><h3>{room.name}</h3><p>Пол {formatNumber(room.area)} м² · стены {formatNumber(room.wallArea)} м² · потолок {formatNumber(room.ceilingArea)} м²</p></div><button className="button secondary" onClick={resetRoom}>Вернуть шаблон помещения</button></header>
        <Toggle label="Учитывать отделку этого помещения" checked={values.enabled!==false} onChange={value=>updateRoom({enabled:value})}/>
        <div className="internal-assembly-grid">
          <fieldset><legend><Layers3/> Пол</legend><SelectField label="Чистовое покрытие" value={values.floorFinish} options={FLOOR} onChange={value=>updateRoom({floorFinish:value,floorSubstrate:value==='tile'&&values.floorSubstrate==='osb12'?'gvl20':values.floorSubstrate})}/><SelectField label="Основание" value={values.floorSubstrate} options={SUBSTRATE} onChange={value=>updateRoom({floorSubstrate:value})}/><Toggle label="Плинтус" checked={values.skirting} onChange={value=>updateRoom({skirting:value})}/><Toggle label="Влажная зона" checked={values.wetZone} onChange={value=>updateRoom({wetZone:value,waterproofFloor:value||values.waterproofFloor})}/>{values.floorFinish==='tile'?<Toggle label="Гидроизоляция пола" checked={values.waterproofFloor} onChange={value=>updateRoom({waterproofFloor:value})}/>:null}<Toggle label="Тёплый пол (передать в инженерию)" checked={values.heatedFloor} onChange={value=>updateRoom({heatedFloor:value})}/><NumberField label="Площадь вручную" value={values.floorArea??room.area} suffix="м²" onChange={value=>updateRoom({floorArea:value})}/>{values.heatedFloor?<p className="assembly-info">Комплектация тёплого пола не задваивается здесь и добавляется в инженерные системы.</p>:null}{values.floorSubstrate==='gvl12'?<p className="assembly-warning">Один слой ГВЛВ 12,5 мм — проектное решение. Для жёсткости основания плитки проверьте допустимость по конструктиву пола.</p>:null}</fieldset>
          <fieldset><legend><Brush/> Стены</legend><SelectField label="Отделка" value={values.wallsFinish} options={WALL} onChange={value=>updateRoom({wallsFinish:value})}/>{values.wallsFinish!=='none'?<SelectField label="Основание / каркас" value={values.wallFrame} options={values.wallsFinish==='timber'?FRAME.filter(item=>item.value!=='metal'):FRAME} onChange={value=>updateRoom({wallFrame:value})}/>:null}{values.wallsFinish==='drywall'?<><SelectField label="Лист" value={values.drywallType} options={BOARD} onChange={value=>updateRoom({drywallType:value})}/><NumberField label="Количество слоёв" value={values.drywallLayers} suffix="слой" step={1} min={1} max={2} onChange={value=>updateRoom({drywallLayers:value})}/><SelectField label="Финиш" value={values.wallFinal} options={FINAL} onChange={value=>updateRoom({wallFinal:value})}/>{values.wallFinal==='paint'?<NumberField label="Слоёв краски" value={values.wallPaintCoats||2} suffix="слой" step={1} min={1} onChange={value=>updateRoom({wallPaintCoats:value})}/>:null}{values.wallFinal==='tile'?<NumberField label="Доля стен под плитку" value={(values.waterproofWallShare||1)*100} suffix="%" step={5} min={5} max={100} onChange={value=>updateRoom({waterproofWallShare:value/100})}/>:null}</>:null}{values.wallsFinish==='timber'?<NumberField label="Слоёв краски" value={values.timberPaintCoats} suffix="слой" step={1} min={0} max={3} onChange={value=>updateRoom({timberPaintCoats:value})}/>:null}<Toggle label="Утепление / звукоизоляция" checked={values.wallInsulation} onChange={value=>updateRoom({wallInsulation:value})}/>{values.wallsFinish==='timber'?<Toggle label="Пароизоляция по проекту" checked={values.wallVaporBarrier} onChange={value=>updateRoom({wallVaporBarrier:value})}/>:null}<NumberField label="Площадь вручную" value={values.wallArea??room.wallArea} suffix="м²" onChange={value=>updateRoom({wallArea:value})}/>{values.wetZone&&values.wallsFinish==='drywall'?<p className="assembly-info"><Droplets/> Во влажной зоне применяйте ГКЛВ/ГВЛВ и гидроизоляцию мест прямого попадания воды.</p>:null}</fieldset>
          <fieldset><legend><CheckCircle2/> Потолок</legend><SelectField label="Вид потолка" value={values.ceilingFinish} options={CEILING} onChange={value=>updateRoom({ceilingFinish:value})}/>{values.ceilingFinish==='timber'?<><SelectField label="Обрешётка" value={values.ceilingFrame} options={CEILING_FRAME} onChange={value=>updateRoom({ceilingFrame:value})}/><Toggle label="Пароизоляция по проекту" checked={values.ceilingVaporBarrier} onChange={value=>updateRoom({ceilingVaporBarrier:value})}/><NumberField label="Слоёв краски" value={values.ceilingPaintCoats} suffix="слой" step={1} min={0} max={3} onChange={value=>updateRoom({ceilingPaintCoats:value})}/></>:null}{values.ceilingFinish==='stretch'?<><SelectField label="Материал полотна" value={values.stretchType} options={STRETCH} onChange={value=>updateRoom({stretchType:value})}/><NumberField label="Светильники" value={values.stretchLights} suffix="шт" step={1} onChange={value=>updateRoom({stretchLights:value})}/><NumberField label="Обходы труб" value={values.stretchPipes} suffix="шт" step={1} onChange={value=>updateRoom({stretchPipes:value})}/><NumberField label="Ниша карниза" value={values.curtainNicheLength} suffix="м" onChange={value=>updateRoom({curtainNicheLength:value})}/></>:null}<NumberField label="Площадь вручную" value={values.ceilingArea??room.ceilingArea} suffix="м²" onChange={value=>updateRoom({ceilingArea:value})}/></fieldset>
        </div>
      </section>:<div className="empty-state">На плане нет площади для внутренней отделки</div>}
    </div>
    <p className="internal-source-note">Ориентировочные цены помечены в прайс-листе. ГВЛВ и мокрые зоны рассчитаны по составу систем КНАУФ, но окончательный несущий узел пола и допустимость одного слоя 12,5 мм подтверждаются проектом.</p>
  </div>;
}
